import { supabase } from './supabaseClient';

// ==================== DEFINIÇÕES DAS ORDENS DE PROCESSO DO TEMPLATE V9 ====================

const TEMPLATE_PROCESS_ORDERS = [
  // ═══════════════════════════ POOL: EDUCAÇÃO (FUNIL INVERTIDO) ═══════════════════════════
  {
    elementId: 'Task_Tag_Educacao',
    elementType: 'serviceTask',
    title: 'CRM — Tag [LEAD_EDUCACAO] (Funil Invertido)',
    objective: 'Registrar lead educacional. ESTRATÉGIA: funil invertido — entrega valor PRIMEIRO, venda é consequência.',
    description: 'Automação CRM: tag [LEAD_EDUCACAO]. Origem: webinar, Aula Secreta, post sobre gestão. REGRA: NÃO VENDER. Primeiro entregar Aula Secreta, depois a venda vem sozinha.',
    steps: [
      { text: 'Verificar origem do lead (webinar, aula, post, anúncio educativo)', done: false },
      { text: 'Adicionar tag [LEAD_EDUCACAO] no CRM', done: false },
      { text: 'Registrar segmento do lead (Contabilidade, Comércio, Clínica, etc.)', done: false },
      { text: 'Disparar cadência do funil invertido (valor → confiança → venda)', done: false },
    ],
    inputs: 'Lead interessado em aprender gestão financeira',
    outputs: 'Lead tagueado, funil invertido iniciado',
    toolsResources: 'CRM, Automação',
    responsible: 'Automação',
    acceptanceCriteria: 'Tag [LEAD_EDUCACAO] aplicada + segmento registrado + cadência disparada',
  },
  {
    elementId: 'Task_Edu_D0_MiniAula',
    elementType: 'sendTask',
    title: 'D0 — Entrega Aula Secreta (NÃO VENDE)',
    objective: 'Primeiro contato: entregar VALOR REAL. NÃO ligar, NÃO vender. Aula Secreta de 20-25 min. No final, CTA leva pro Curso completo.',
    description: 'WhatsApp automático com Aula Secreta (20-25 min). O lead aplica no próprio negócio e VÊ resultado. No final da aula, CTA leva pro Curso completo (+ bônus Software). Trigger: se assistir 10+ min → Closer notificado.',
    steps: [
      { text: 'Enviar WhatsApp: "Separei uma Aula Secreta exclusiva pra você" + link', done: false },
      { text: 'Aula Secreta (20-25 min): Erros fatais → O que é DRE → Passo a passo prático → Ler resultado', done: false },
      { text: 'CTA FINAL da aula: "Isso foi só 1 módulo. Quero o Curso Completo →" (leva pro Curso + bônus Software)', done: false },
      { text: 'Tom: professor, não vendedor. "Depois me conta como foi!"', done: false },
      { text: 'NÃO ligar. NÃO mencionar produto. Só entregar valor.', done: false },
      { text: 'TRIGGER 10 MIN: Se lead assistiu 10+ min → Closer envia "Vi que você tá assistindo! Qualquer dúvida, me chama."', done: false },
      { text: 'Se assistiu 100% (chegou no CTA) → lead quente, priorizar no D1', done: false },
      { text: 'Se clicou no CTA "Quero o Curso" → lead PRONTO, Closer liga imediatamente', done: false },
    ],
    inputs: 'Lead tagueado [LEAD_EDUCACAO]',
    outputs: 'Aula Secreta entregue, lead direcionado pro Curso completo no final',
    toolsResources: 'WhatsApp, Aula Secreta (vídeo 20-25 min), Automação, Plataforma com watch-time tracking',
    responsible: 'Automação',
    acceptanceCriteria: 'Aula Secreta enviada, watch-time monitorado, Closer notificado se 10+ min, CTA pro Curso no final',
  },
  {
    elementId: 'Task_Edu_D1_Followup',
    elementType: 'sendTask',
    title: 'D1 — Follow-up Consultivo: "Conseguiu Aplicar?"',
    objective: 'Follow-up genuíno sobre a Aula Secreta. Ajudar de verdade. Ainda NÃO vende.',
    description: 'WhatsApp: "Conseguiu montar o DRE?" Se fez → parabenizar, perguntar resultado. Se não → ajudar com dúvidas. Se o lead perguntar "como automatizar?" → "Posso te mostrar amanhã em 15 min."',
    steps: [
      { text: 'WhatsApp: "E aí [Nome], conseguiu montar o DRE?"', done: false },
      { text: 'Se fez: "Qual foi o resultado? Lucro ou prejuízo?" → conversa natural', done: false },
      { text: 'Se não fez: "Normal, posso te ajudar. Qual sua maior dúvida?"', done: false },
      { text: 'Se perguntar como automatizar: "Posso te mostrar amanhã em 15 min"', done: false },
      { text: 'REGRA: Se pedir ajuda, AJUDE. Confiança primeiro, venda depois.', done: false },
    ],
    inputs: 'Lead que recebeu Aula Secreta no D0',
    outputs: 'Lead engajado com conteúdo, confiança construída',
    toolsResources: 'WhatsApp, CRM',
    responsible: 'Closer',
    acceptanceCriteria: 'Follow-up consultivo realizado, sem pressão de venda',
  },
  {
    elementId: 'Task_Edu_D3_Demo',
    elementType: 'task',
    title: 'D3 — Demo Fyness: "Automatize o que Você Aprendeu"',
    objective: 'PONTO DE VIRADA: mostrar que o Fyness automatiza o DRE que o lead fez na mão. A venda é consequência natural.',
    description: 'O lead já APRENDEU o conceito (DRE). Agora mostrar como AUTOMATIZAR com Fyness. Demo de 15 min: lançar receita por áudio → gráfico aparece → "Esse é o DRE que você fez na mão, mas automático."',
    steps: [
      { text: 'WhatsApp: "Lembra do DRE que você montou? Imagina falando por áudio e pronto."', done: false },
      { text: 'Demo (15 min): Abrir Fyness → lançar receita por ÁUDIO (momento WOW)', done: false },
      { text: 'Mostrar DRE automático + Fluxo de Caixa + Alertas de vencimento', done: false },
      { text: 'Oferta natural: "Quer se inscrever no curso? O Fyness já vem dentro." (não empurrar)', done: false },
      { text: 'Reforçar: "O software que você acabou de ver está DENTRO do curso. Você aprende o método e já usa a ferramenta."', done: false },
    ],
    inputs: 'Lead que aprendeu DRE na Aula Secreta e construiu confiança',
    outputs: 'Lead viu o valor do software integrado, decisão sobre o Curso',
    toolsResources: 'Zoom/Google Meet, Fyness (conta demo), Demo por Setor',
    responsible: 'Closer',
    acceptanceCriteria: 'Demo realizada, decisão do lead registrada no CRM',
  },
  {
    elementId: 'Task_Edu_D7_Escassez',
    elementType: 'sendTask',
    title: 'D7 — Escassez: "Turma Fecha" + Última Tentativa',
    objective: 'Última tentativa para leads que não converteram no D3. Escassez real: vagas limitadas.',
    description: 'WhatsApp de escassez: "Turma fecha em X dias." + 1 ligação final se não respondeu em 4h. O lead já recebeu valor (Aula Secreta) e viu a demo — tem tudo pra decidir.',
    steps: [
      { text: 'WhatsApp: "Última mensagem — vagas da turma fechando. Posso reservar sua vaga?"', done: false },
      { text: 'Se não respondeu em 4h: 1 ligação final', done: false },
      { text: 'Se respondeu/atendeu: Fechar Checkout do Curso', done: false },
      { text: 'Se ignorou: Encaminhar para Nurturing (não insistir mais)', done: false },
    ],
    inputs: 'Lead que não quis o Curso no D3',
    outputs: 'Lead convertido ou encaminhado para Nurturing',
    toolsResources: 'WhatsApp, Telefone, CRM',
    responsible: 'Closer',
    acceptanceCriteria: 'Última tentativa realizada, destino do lead definido',
  },
  {
    elementId: 'Task_Edu_Nurturing',
    elementType: 'serviceTask',
    title: 'Nurturing Educação — Ciclo Invertido Contínuo',
    objective: 'Lead não converteu mas recebeu valor. Manter no ciclo invertido: continuar entregando conteúdo educativo até reconversão.',
    description: 'Grupo de nurturing educativo. Cadência semanal: SEG=dica gestão, QUA=case resultado, SEX=Aula Secreta. O funil invertido não para — cada conteúdo é uma nova oportunidade de o lead pedir a solução.',
    steps: [
      { text: 'Adicionar lead ao grupo WhatsApp de nurturing educação', done: false },
      { text: 'Cadência semanal: SEG=dica gestão, QUA=case, SEX=Aula Secreta/checklist', done: false },
      { text: 'Campanhas sazonais: "Nova turma aberta" (Black Friday, Ano Novo)', done: false },
      { text: 'Se clicar 2x em conteúdo → Ligar (lead pediu atenção)', done: false },
      { text: 'CRM: tag [LEAD_EDUCACAO_NURTURING]', done: false },
    ],
    inputs: 'Lead que não converteu após cadência D0-D7 do funil invertido',
    outputs: 'Lead em nurturing ativo, ciclo invertido contínuo',
    toolsResources: 'WhatsApp, CRM, Automação de conteúdo',
    responsible: 'Automação / Marketing',
    acceptanceCriteria: 'Lead no grupo, recebendo conteúdo semanal, engajamento monitorado',
  },

  // ----------- EDUCAÇÃO: ABANDONO DE CARRINHO -----------
  {
    elementId: 'Task_Edu_Abandono_30min',
    elementType: 'sendTask',
    title: '30min — Recovery 1: "Vi Que Faltou Pouco"',
    objective: 'Recuperar lead que iniciou checkout do curso mas não finalizou. Tom amigável, assume problema técnico.',
    description: 'WhatsApp automático 30 min após abandono. Assume falha técnica (internet, celular). Link direto pro checkout sem refazer dados. NÃO pressiona, NÃO dá desconto.',
    steps: [
      { text: 'WhatsApp: "Vi que você começou a se inscrever mas não finalizou. Acontece!"', done: false },
      { text: 'Incluir link direto pro checkout (dados preservados)', done: false },
      { text: '"Seu acesso tá reservado por mais algumas horas"', done: false },
      { text: 'Tom: amigável, assume problema técnico. NÃO pressionar.', done: false },
    ],
    inputs: 'Lead que abandonou checkout do curso (trigger automático)',
    outputs: 'Link de recuperação enviado',
    toolsResources: 'WhatsApp, Automação, Plataforma de checkout',
    responsible: 'Automação',
    acceptanceCriteria: 'Mensagem enviada em até 30 min após abandono, link funcional',
  },
  {
    elementId: 'Task_Edu_Abandono_24h',
    elementType: 'sendTask',
    title: '24h — Recovery 2: Depoimento + Reforço do Bônus',
    objective: 'Prova social + reforço que Software vem de bônus. Aumentar valor percebido sem baixar preço.',
    description: 'WhatsApp com case real de empresário do mesmo segmento + lembrete do bônus (Fyness de graça). Se respondeu interessado → Closer liga (máx 1).',
    steps: [
      { text: 'Enviar case real do mesmo segmento: "Fulano identificou R$ 2.800 em gastos invisíveis"', done: false },
      { text: 'Reforçar bônus: "Assinando, você GANHA o Fyness (software) de bônus"', done: false },
      { text: 'Link do checkout: "Seu acesso ainda tá reservado"', done: false },
      { text: 'Se respondeu interessado: Closer liga (máx 1 ligação)', done: false },
    ],
    inputs: 'Lead não recuperou no recovery 1 (30min)',
    outputs: 'Lead impactado por prova social + bônus reforçado',
    toolsResources: 'WhatsApp, Cases de Sucesso por Segmento, CRM',
    responsible: 'Automação / Closer (se respondeu)',
    acceptanceCriteria: 'Case enviado do segmento correto, bônus mencionado',
  },
  {
    elementId: 'Task_Edu_Abandono_48h',
    elementType: 'sendTask',
    title: '48h — Recovery 3: Última Chance + Ligação Final',
    objective: 'Última tentativa. Escassez real (acesso expira) + stack completo do que o lead ganha + ligação do Closer.',
    description: 'WhatsApp de escassez: acesso reservado expira hoje. Resumo de tudo (curso + Fyness bônus + comunidade + mentorias). Se não respondeu em 4h → 1 ligação final do Closer. Se não converter → volta ao funil normal.',
    steps: [
      { text: 'WhatsApp: "Último aviso — seu acesso reservado expira HOJE"', done: false },
      { text: 'Stack completo: Curso + Fyness bônus + Comunidade + Mentorias', done: false },
      { text: '"Depois disso, só na próxima turma (e o preço pode mudar)"', done: false },
      { text: 'Se não respondeu em 4h: 1 ligação final do Closer', done: false },
      { text: 'Ligação: "Vi que você quase se inscreveu. Aconteceu algo? Posso ajudar com alguma dúvida?"', done: false },
      { text: 'Se não converter: NÃO insistir. Lead volta ao funil (D1 follow-up)', done: false },
    ],
    inputs: 'Lead não recuperou no recovery 2 (24h)',
    outputs: 'Lead convertido ou volta ao funil normal',
    toolsResources: 'WhatsApp, Telefone, CRM',
    responsible: 'Automação + Closer (ligação final)',
    acceptanceCriteria: 'Última tentativa realizada, destino do lead definido (cliente ou volta ao funil)',
  },

  // ----------- EDUCAÇÃO: RECOVERY 100% SEM CTA -----------
  {
    elementId: 'Task_Edu_100_Followup',
    elementType: 'sendTask',
    title: '2h — Recovery: "Qual Parte Foi Mais Útil?"',
    objective: 'Lead assistiu 100% da Aula Secreta mas NÃO clicou no CTA. Enviar follow-up consultivo 2h depois pra reaquecer.',
    description: 'Lead investiu 20-25 min e viu o CTA mas não agiu. A pergunta "qual parte mais útil?" faz o lead REVIVER o valor absorvido. Se responder, a porta do curso abre naturalmente.',
    steps: [
      { text: 'WhatsApp: "Vi que você assistiu a Aula Secreta inteira! Qual parte foi mais útil pro seu negócio?"', done: false },
      { text: 'Se respondeu DRE: "Quer ver o Fyness montando o DRE automático? Posso mostrar em 15 min."', done: false },
      { text: 'Se respondeu fluxo de caixa: "Tem um módulo inteiro sobre isso no curso. Quer ver?"', done: false },
      { text: 'Se fez pergunta: Responder e direcionar pro curso naturalmente', done: false },
      { text: 'Se NÃO respondeu: Não insistir. D1 Follow-up cuida amanhã.', done: false },
      { text: 'CRM: Tag [ASSISTIU_100_SEM_CTA] — lead de alta intenção', done: false },
    ],
    inputs: 'Lead que assistiu 100% da Aula Secreta sem clicar no CTA (trigger automático)',
    outputs: 'Lead reengajado ou seguindo pro D1 normalmente',
    toolsResources: 'WhatsApp, CRM, Automação (watch-time tracking)',
    responsible: 'Automação + Closer (se respondeu)',
    acceptanceCriteria: 'Mensagem enviada 2h após 100%, tag aplicada no CRM',
  },

  // ═══════════════════════════ POOL: INDICAÇÃO ═══════════════════════════
  {
    elementId: 'Task_Tag_Ativo',
    elementType: 'serviceTask',
    title: 'CRM — Cadastro Lead Indicação Ativa',
    objective: 'Cadastrar lead de indicação ativa no CRM com tag do parceiro e SLA < 30 min.',
    description: 'Automação CRM: cadastrar lead, adicionar tag [INDICAÇÃO: NOME_DO_PARCEIRO], definir prioridade SLA < 30 min, notificar vendedor.',
    steps: [
      { text: 'Cadastrar lead no CRM com dados recebidos', done: false },
      { text: 'Adicionar tag obrigatória [INDICAÇÃO: NOME_DO_PARCEIRO]', done: false },
      { text: 'Definir prioridade: SLA < 30 min', done: false },
      { text: 'Notificar vendedor responsável', done: false },
    ],
    inputs: 'Dados do lead, nome do parceiro que indicou',
    outputs: 'Lead cadastrado com tag e prioridade, vendedor notificado',
    toolsResources: 'CRM, Sistema de notificações',
    responsible: 'Automação / Vendedor',
    acceptanceCriteria: 'Lead tagueado corretamente, vendedor acionado em < 30 min',
  },
  {
    elementId: 'Task_Tag_Passivo',
    elementType: 'serviceTask',
    title: 'CRM — Cadastro Lead Indicação Passiva',
    objective: 'Cadastrar lead que veio espontaneamente mencionando um parceiro.',
    description: 'Perguntar nome do parceiro, cadastrar lead no CRM com tag [INDICAÇÃO: NOME_DO_PARCEIRO], resposta em tempo real.',
    steps: [
      { text: 'Perguntar: "Qual nome do parceiro que te indicou?"', done: false },
      { text: 'Cadastrar lead no CRM', done: false },
      { text: 'Adicionar tag [INDICAÇÃO: NOME_DO_PARCEIRO]', done: false },
      { text: 'Responder em tempo real (WhatsApp/Instagram)', done: false },
    ],
    inputs: 'Mensagem do lead, nome do parceiro',
    outputs: 'Lead cadastrado e tagueado no CRM',
    toolsResources: 'CRM, WhatsApp, Instagram',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Lead cadastrado com tag correta do parceiro',
  },
  {
    elementId: 'Task_QuebraGelo_Ativo',
    elementType: 'userTask',
    title: 'WhatsApp Áudio — Script Ativo (Indicação)',
    objective: 'Transferir a confiança do parceiro para o vendedor via áudio pessoal no WhatsApp.',
    description: 'Enviar áudio mencionando o parceiro que indicou, usando autoridade emprestada para criar rapport imediato.',
    steps: [
      { text: 'Gravar áudio personalizado mencionando nome do parceiro', done: false },
      { text: 'Usar script: mencionar que o parceiro pediu atendimento VIP', done: false },
      { text: 'Perguntar se pode falar 2 minutinhos', done: false },
      { text: 'Registrar resultado do contato no CRM', done: false },
    ],
    inputs: 'Dados do lead, nome do parceiro, contexto da indicação',
    outputs: 'Primeiro contato realizado, rapport estabelecido',
    toolsResources: 'WhatsApp, CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Áudio enviado, lead respondeu ou visualizou',
  },
  {
    elementId: 'Task_QuebraGelo_Passivo',
    elementType: 'userTask',
    title: 'WhatsApp Áudio — Script Passivo (Indicação)',
    objective: 'Validar a relação com o parceiro e mostrar resultado dele para o lead que veio espontaneamente.',
    description: 'Receber o lead que veio por indicação passiva, validar relação e direcionar para demonstração do resultado do parceiro.',
    steps: [
      { text: 'Responder mencionando o parceiro como "grande parceiro nosso"', done: false },
      { text: 'Perguntar se o parceiro mostrou o sistema funcionando', done: false },
      { text: 'Direcionar conversa para demonstração', done: false },
    ],
    inputs: 'Mensagem do lead, nome do parceiro',
    outputs: 'Lead engajado e direcionado para demo',
    toolsResources: 'WhatsApp, CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Lead respondeu positivamente e agendou/aceitou demo',
  },
  {
    elementId: 'Task_D0_Ligacao_Indicacao',
    elementType: 'userTask',
    title: 'D0 — Ligação Minuto 0 (Indicação)',
    objective: 'Fazer contato imediato transferindo autoridade do parceiro.',
    description: 'Ligar no minuto 0 usando script de autoridade emprestada. Perguntar se está na frente do computador para demonstração.',
    steps: [
      { text: 'Ligar imediatamente após cadastro (Min 0)', done: false },
      { text: 'Usar script: "[Parceiro] me falou muito bem da sua empresa"', done: false },
      { text: 'Perguntar se está na frente do computador', done: false },
      { text: 'Se atendeu → qualificação. Se não → WhatsApp áudio', done: false },
    ],
    inputs: 'Dados do lead, nome do parceiro',
    outputs: 'Contato realizado, lead qualificado ou follow-up agendado',
    toolsResources: 'Telefone, CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Ligação realizada em < 5 min após cadastro',
  },
  {
    elementId: 'Task_D0_Qualifica_Indicacao',
    elementType: 'userTask',
    title: 'D0 — Qualifica (Autoridade Parceiro)',
    objective: 'Qualificar o lead usando a confiança do parceiro como moeda de troca.',
    description: 'Se atendeu a ligação, fazer a "carteirada" do parceiro e qualificar perguntando se usa planilha ou caderno.',
    steps: [
      { text: 'Mencionar que o parceiro pediu atendimento VIP', done: false },
      { text: 'Perguntar: "Você tá usando planilha hoje ou caderno?"', done: false },
      { text: 'Identificar dor principal do lead', done: false },
      { text: 'Direcionar para demonstração contextualizada', done: false },
    ],
    inputs: 'Lead atendeu a ligação, contexto do parceiro',
    outputs: 'Lead qualificado, dor identificada, demo agendada',
    toolsResources: 'Telefone, CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Lead qualificado com dor identificada',
  },
  {
    elementId: 'Task_D0_Instagram_Indicacao',
    elementType: 'serviceTask',
    title: 'D0 — Instagram Social Selling (Indicação)',
    objective: 'Criar proximidade social com o lead antes da venda, mostrando que você é real.',
    description: 'No final do dia D0: seguir a empresa/perfil do lead no Instagram e curtir 2 fotos recentes. NÃO mandar DM — isso é só warming.',
    steps: [
      { text: 'Encontrar perfil do lead no Instagram', done: false },
      { text: 'Seguir a empresa/perfil', done: false },
      { text: 'Curtir exatamente 2 fotos recentes (não mais)', done: false },
      { text: 'NÃO mandar DM — é só warming', done: false },
    ],
    inputs: 'Nome do lead, empresa, perfil Instagram',
    outputs: 'Perfil seguido, 2 fotos curtidas',
    toolsResources: 'Instagram',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Perfil seguido e 2 fotos curtidas no mesmo dia',
  },
  {
    elementId: 'Task_D0_WhatsApp1_Indicacao',
    elementType: 'sendTask',
    title: 'D0 — WhatsApp 1 (Min 15) — Áudio Pessoal',
    objective: 'Reforçar autoridade emprestada via áudio pessoal caso não atenda a ligação.',
    description: 'Minuto 15: enviar áudio mencionando que o parceiro passou o contato e que prometeu atendimento VIP.',
    steps: [
      { text: 'Aguardar 15 min sem resposta na ligação', done: false },
      { text: 'Gravar áudio pessoal mencionando o parceiro', done: false },
      { text: 'Enviar via WhatsApp com tom pessoal', done: false },
      { text: 'Registrar tentativa no CRM', done: false },
    ],
    inputs: 'Lead não atendeu ligação, dados do parceiro',
    outputs: 'Áudio enviado no WhatsApp',
    toolsResources: 'WhatsApp, CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Áudio enviado em até 15 min após tentativa de ligação',
  },
  {
    elementId: 'Task_D1_WhatsApp2_Indicacao',
    elementType: 'userTask',
    title: 'D1 — Ligação + Cobrança do Amigo',
    objective: 'Ligar primeiro para cobrar usando compromisso social. Se não atender, enviar WhatsApp.',
    description: 'Dia 1: ligar mencionando que o parceiro perguntou se já se falaram. Se não atender, enviar WhatsApp com áudio de 30s.',
    steps: [
      { text: 'LIGAR para o lead — script: "Oi [nome], o [parceiro] me pediu pra te ligar..."', done: false },
      { text: 'Se atendeu: conduzir conversa, agendar demo se possível', done: false },
      { text: 'Se NÃO atendeu: enviar WhatsApp com cobrança do amigo', done: false },
      { text: 'Registrar no CRM: D1 — ligação + WhatsApp', done: false },
    ],
    inputs: 'Lead não respondeu D0, telefone do lead',
    outputs: 'Ligação realizada, WhatsApp enviado se necessário',
    toolsResources: 'Telefone, WhatsApp, CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Ligação realizada no D1, WhatsApp enviado se não atendeu',
  },
  {
    elementId: 'Task_D3_WhatsApp3_Indicacao',
    elementType: 'userTask',
    title: 'D3 — Ligação + Bastidor do Parceiro',
    objective: 'Ligar com prova social visual do parceiro. Se não atender, enviar WhatsApp com print/vídeo.',
    description: 'Dia 3: ligar mostrando resultado real do parceiro com Fyness. Se não atender, enviar print/vídeo por WhatsApp.',
    steps: [
      { text: 'LIGAR para o lead — script: "Vi que o [parceiro] bateu recorde de faturamento..."', done: false },
      { text: 'Se atendeu: mostrar resultado do parceiro, propor demo', done: false },
      { text: 'Se NÃO atendeu: enviar WhatsApp com print/vídeo do parceiro', done: false },
      { text: 'Registrar no CRM: D3 — ligação + WhatsApp', done: false },
    ],
    inputs: 'Print/vídeo do parceiro, telefone do lead',
    outputs: 'Ligação realizada, prova social enviada se necessário',
    toolsResources: 'Telefone, WhatsApp, Material do parceiro, CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Ligação realizada no D3, WhatsApp com prova visual se não atendeu',
  },
  {
    elementId: 'Task_D6_WhatsApp4_Indicacao',
    elementType: 'userTask',
    title: 'D6 — Ligação + Ultimato VIP',
    objective: 'Ligar com escassez e benefício exclusivo. Se não atender, enviar WhatsApp com ultimato.',
    description: 'Dia 6: ligar comunicando que condição especial expira amanhã. Se não atender, enviar WhatsApp com ultimato.',
    steps: [
      { text: 'LIGAR para o lead — script: "Última chance de garantir isenção de taxa..."', done: false },
      { text: 'Se atendeu: apresentar benefício exclusivo, fechar ou agendar', done: false },
      { text: 'Se NÃO atendeu: enviar WhatsApp com ultimato VIP', done: false },
      { text: 'Registrar no CRM: D6 — ligação + ultimato', done: false },
    ],
    inputs: 'Lead sem resposta há 6 dias, telefone do lead',
    outputs: 'Ligação realizada, ultimato enviado se necessário',
    toolsResources: 'Telefone, WhatsApp, CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Ligação realizada no D6, WhatsApp de escassez se não atendeu',
  },
  {
    elementId: 'Task_D10_WhatsApp5_Indicacao',
    elementType: 'sendTask',
    title: 'D10 — WhatsApp 5 (Manhã) — Break-up Elegante',
    objective: 'Encerrar ciclo de venda ativa sem queimar a ponte com lead nem parceiro.',
    description: 'Dia 10 manhã: break-up elegante mencionando o parceiro para preservar o relacionamento dele. Deixar porta aberta.',
    steps: [
      { text: 'Enviar mensagem de encerramento elegante', done: false },
      { text: 'Mencionar o parceiro para preservar o relacionamento', done: false },
      { text: 'Deixar contato salvo como último recurso', done: false },
      { text: 'Registrar no CRM: Break-up enviado', done: false },
    ],
    inputs: 'Lead sem resposta há 10 dias',
    outputs: 'Ciclo encerrado profissionalmente, porta aberta',
    toolsResources: 'WhatsApp, CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Break-up enviado no D10, CRM atualizado',
  },
  {
    elementId: 'Task_AvisaParceiro',
    elementType: 'sendTask',
    title: 'Avisar Parceiro (Validar Ego)',
    objective: 'Validar ego do parceiro e estimular novas indicações.',
    description: 'Enviar mensagem ao parceiro avisando que o lead converteu e está sendo bem cuidado. Pedir mais indicações.',
    steps: [
      { text: 'Enviar mensagem agradecendo a indicação', done: false },
      { text: 'Informar que o lead já é cliente', done: false },
      { text: 'Pedir mais indicações de forma natural', done: false },
      { text: 'Registrar indicação bem-sucedida no CRM', done: false },
    ],
    inputs: 'Lead converteu, dados do parceiro',
    outputs: 'Parceiro notificado, estímulo para novas indicações',
    toolsResources: 'WhatsApp, CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Parceiro avisado no mesmo dia da conversão',
  },
  {
    elementId: 'Task_FlashDemo_Indicacao',
    elementType: 'userTask',
    title: 'Demo Contextualizada (Indicação)',
    objective: 'Mostrar o produto funcionando com foco na dor que o parceiro já validou.',
    description: 'Gravar tela mostrando a funcionalidade que o parceiro mais gosta, NÃO demo genérica. Usar contexto do parceiro.',
    steps: [
      { text: 'Identificar a funcionalidade favorita do parceiro', done: false },
      { text: 'Gravar demo com contexto do parceiro: "O [Parceiro] gosta disso aqui"', done: false },
      { text: 'Enviar áudio/vídeo de 20-30s', done: false },
      { text: 'Perguntar se o lead busca essa agilidade', done: false },
      { text: 'Bônus Educação: "Assinando, você ganha acesso à Plataforma de Educação — cursos, comunidade, mentorias. Tudo de bônus."', done: false },
    ],
    inputs: 'Funcionalidade favorita do parceiro, dados do lead',
    outputs: 'Demo contextualizada enviada, interesse identificado',
    toolsResources: 'Gravação de tela, WhatsApp, Fyness',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Demo personalizada enviada (não genérica)',
  },
  {
    elementId: 'Task_SelecaoMotivo_Indicacao',
    elementType: 'userTask',
    title: 'CRM — Selecionar Motivo da Perda (Indicação)',
    objective: 'Registrar motivo real da perda para análise de padrões e avisar parceiro.',
    description: 'Selecionar motivo no CRM: Ghosting, Preço, Concorrência, Desqualificado, Timing, Outro. Avisar parceiro que lead não converteu.',
    steps: [
      { text: 'Selecionar motivo da perda no CRM', done: false },
      { text: 'Adicionar notas com contexto da negociação', done: false },
      { text: 'Manter tag [INDICAÇÃO: NOME_DO_PARCEIRO]', done: false },
      { text: 'Avisar parceiro que lead não converteu (sem detalhes)', done: false },
    ],
    inputs: 'Histórico de tentativas de contato',
    outputs: 'Lead marcado como LOST com motivo + parceiro avisado',
    toolsResources: 'CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Motivo registrado, parceiro avisado',
  },
  {
    elementId: 'Task_GrupoNurturing_Indicacao',
    elementType: 'serviceTask',
    title: 'Grupo WhatsApp Nurturing (Indicação)',
    objective: 'Manter lead aquecido em grupo de nurturing com promoções e cases do parceiro.',
    description: 'Adicionar lead em grupo WhatsApp para receber promoções, cases de sucesso e ofertas de reativação. Considerado perdido apenas se bloquear/sair.',
    steps: [
      { text: 'Adicionar lead ao grupo de WhatsApp Nurturing', done: false },
      { text: 'Configurar envio semanal de cases de sucesso', done: false },
      { text: 'Incluir promoções especiais mensais', done: false },
      { text: 'Monitorar se lead bloqueia ou sai do grupo', done: false },
    ],
    inputs: 'Lead que respondeu ao break-up',
    outputs: 'Lead no grupo de nurturing ativo',
    toolsResources: 'WhatsApp, CRM',
    responsible: 'Automação / Marketing',
    acceptanceCriteria: 'Lead adicionado ao grupo com sucesso',
  },

  // ═══════════════════════════ POOL: CONTEÚDO ═══════════════════════════
  {
    elementId: 'Task_ManyChat_Pessoal',
    elementType: 'serviceTask',
    title: 'ManyChat — Responde Comentário + Pede Zap (Pessoal)',
    objective: 'Capturar contato WhatsApp de leads pessoais via automação ManyChat no Instagram.',
    description: 'Automação ManyChat: responde comentário de forma natural, usa DM para pedir WhatsApp do lead pessoa física.',
    steps: [
      { text: 'Detectar comentário no post/reels via ManyChat', done: false },
      { text: 'Enviar resposta automática no comentário', done: false },
      { text: 'Enviar DM pedindo WhatsApp', done: false },
      { text: 'Registrar contato no CRM quando receber o número', done: false },
    ],
    inputs: 'Comentário no Instagram',
    outputs: 'Número de WhatsApp capturado',
    toolsResources: 'ManyChat, Instagram, CRM',
    responsible: 'Automação / Marketing',
    acceptanceCriteria: 'WhatsApp capturado e registrado no CRM',
  },
  {
    elementId: 'Task_WhatsApp_Pessoal',
    elementType: 'userTask',
    title: 'D0 — WhatsApp Autoridade — Sócio (Híbrido)',
    objective: 'Sócio faz APENAS o primeiro contato (D0) com autoridade pessoal, depois transfere para o Vendedor.',
    description: 'Modelo Híbrido: Sócio envia mensagem de autoridade no WhatsApp ("Vi que interagiu no meu Story"), responde 1x se tiver dúvida, e faz handoff pro Vendedor. Vendedor assume demo + follow-up + fechamento.',
    steps: [
      { text: 'SÓCIO envia mensagem D0 referenciando o conteúdo', done: false },
      { text: 'Se lead responder com dúvida → Sócio responde 1x com credibilidade', done: false },
      { text: 'HANDOFF: Sócio apresenta o Vendedor na conversa', done: false },
      { text: 'Vendedor entra: "Sou o [Vendedor], o [Sócio] me pediu pra te mostrar..."', done: false },
      { text: 'A partir daqui VENDEDOR é dono do lead (demo, follow-up, fechamento)', done: false },
    ],
    inputs: 'WhatsApp do lead, conteúdo de origem',
    outputs: 'Handoff feito — Vendedor assumiu o lead',
    toolsResources: 'WhatsApp, CRM',
    responsible: 'Sócio (D0) → Vendedor (demo em diante)',
    acceptanceCriteria: 'Sócio fez D0, handoff realizado, Vendedor assumiu',
  },
  {
    elementId: 'Task_FlashDemo_Pessoal',
    elementType: 'userTask',
    title: 'D0 — Flash Demo pelo Vendedor (Híbrido)',
    objective: 'Vendedor conduz a demo usando autoridade emprestada do sócio — efeito espelho.',
    description: 'Vendedor faz a demo mostrando como o SÓCIO usa o Fyness no dia a dia. Usa frases como "O [Sócio] usa assim..." para manter a autoridade emprestada. Foco no bastidor, não em features genéricas.',
    steps: [
      { text: 'Vendedor se apresenta referenciando o sócio', done: false },
      { text: 'Mostrar como o SÓCIO usa o Fyness (efeito espelho)', done: false },
      { text: 'Gravar demo rápida (20-30s) personalizada na dor do lead', done: false },
      { text: 'Fechar: "Quer testar 7 dias grátis igual o [Sócio] quando começou?"', done: false },
      { text: 'Bônus Educação: "Assinando, você ganha acesso à Plataforma de Educação — cursos, comunidade, mentorias. Tudo de bônus."', done: false },
    ],
    inputs: 'Lead transferido do sócio, dor identificada',
    outputs: 'Demo personalizada enviada pelo Vendedor, interesse confirmado',
    toolsResources: 'WhatsApp, Gravação de tela, Fyness',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Vendedor conduziu demo usando autoridade do sócio, lead engajado',
  },
  {
    elementId: 'Task_SDR_Empresa',
    elementType: 'serviceTask',
    title: 'Qualificação Automática via DM (Conteúdo Empresa)',
    objective: 'Qualificar leads empresa automaticamente via chatbot 24/7, sem intervenção humana.',
    description: 'Bot (ManyChat/Chatbot) responde DMs automaticamente: detecta palavras-chave, faz pergunta de qualificação, captura WhatsApp de decisores e descarta curiosos.',
    steps: [
      { text: 'Configurar detecção de palavras-chave (financeiro, gestão, sistema)', done: false },
      { text: 'Criar fluxo de qualificação automática no ManyChat', done: false },
      { text: 'Perguntar automaticamente: "Você é o dono ou cuida do financeiro?"', done: false },
      { text: 'Se decisor → pedir WhatsApp e registrar no CRM com tag [CONTEÚDO: EMPRESA]', done: false },
      { text: 'Se não decisor → encerrar com mensagem educada', done: false },
    ],
    inputs: 'DM de empresa no Instagram (automático)',
    outputs: 'Lead qualificado com WhatsApp no CRM, ou descartado',
    toolsResources: 'ManyChat, Instagram API, CRM',
    responsible: 'Automação / Marketing',
    acceptanceCriteria: 'Bot qualificando 24/7, taxa de captura WhatsApp > 30%',
  },
  {
    elementId: 'Task_WhatsApp_Empresa',
    elementType: 'userTask',
    title: 'D0 — WhatsApp Abordagem Consultiva (Conteúdo Empresa)',
    objective: 'Abordar empresa com tom consultivo focado em resolver problema de gestão.',
    description: 'Mensagem consultiva no WhatsApp: entender a operação, quantos funcionários, qual sistema usa hoje, qual a dor principal.',
    steps: [
      { text: 'Enviar mensagem com tom consultivo (não vendedor)', done: false },
      { text: 'Perguntar sobre operação atual e ferramentas usadas', done: false },
      { text: 'Identificar gaps e dores específicas', done: false },
      { text: 'Direcionar para demo focada na dor', done: false },
    ],
    inputs: 'Dados de qualificação automática',
    outputs: 'Dores mapeadas, demo agendada',
    toolsResources: 'WhatsApp, CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Conversa consultiva realizada, dor clara identificada',
  },
  {
    elementId: 'Task_FlashDemo_Empresa',
    elementType: 'userTask',
    title: 'D0 — Flash Demo Função/Dor (Conteúdo Empresa)',
    objective: 'Demonstrar a funcionalidade específica que resolve a dor da empresa.',
    description: 'Demo focada na dor identificada: se é DRE, mostrar DRE. Se é fluxo de caixa, mostrar fluxo. Não demo genérica.',
    steps: [
      { text: 'Selecionar funcionalidade que resolve a dor identificada', done: false },
      { text: 'Gravar demo de 30-60s da funcionalidade específica', done: false },
      { text: 'Enviar com contexto: "Vi que sua dor é X, olha como resolve"', done: false },
      { text: 'Fechar: "Quer testar 7 dias grátis?"', done: false },
      { text: 'Bônus Educação: "Assinando, você ganha acesso à Plataforma de Educação — cursos, comunidade, mentorias. Tudo de bônus."', done: false },
    ],
    inputs: 'Dor identificada na conversa consultiva',
    outputs: 'Demo funcional enviada, proposta de trial feita',
    toolsResources: 'Gravação de tela, WhatsApp, Fyness',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Demo enviada focada na funcionalidade relevante',
  },
  {
    elementId: 'Task_Cont_D1',
    elementType: 'userTask',
    title: 'D1 — Ligação + Reengajamento (Vendedor)',
    objective: 'Vendedor liga para reengajar o lead que o sócio abriu. WhatsApp só como backup.',
    description: 'Dia 1: CLOSER liga para o lead referenciando a equipe do sócio. Se não atender, envia WhatsApp com print + link trial. Sócio não participa do follow-up.',
    steps: [
      { text: 'Vendedor liga para o lead (prioridade #1)', done: false },
      { text: 'Se atender: "Aqui é o [Vendedor] da equipe do [Sócio]" + resultado de cliente similar', done: false },
      { text: 'Se NÃO atender: enviar WhatsApp com print + link trial', done: false },
      { text: 'Registrar no CRM: D1 Conteúdo — ligação ou WhatsApp', done: false },
    ],
    inputs: 'Lead não fechou na demo, print de cliente similar',
    outputs: 'Ligação realizada ou WhatsApp enviado como backup',
    toolsResources: 'Telefone, WhatsApp, Banco de prints, CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Vendedor fez tentativa de ligação no D1. WhatsApp enviado se não atendeu.',
  },
  {
    elementId: 'Task_Cont_D3',
    elementType: 'userTask',
    title: 'D3 — Ligação + Bastidor do Sócio (Vendedor)',
    objective: 'Vendedor usa resultado REAL do sócio como prova (não case genérico). Lead segue o sócio → efeito espelho.',
    description: 'Dia 3: Vendedor liga mostrando resultado real do SÓCIO. "O [Sócio] cortou R$ 4.800 de gastos invisíveis." Lead quer copiar o ídolo. Se não atender, WhatsApp com print do Story.',
    steps: [
      { text: 'Vendedor liga referenciando resultado real do SÓCIO', done: false },
      { text: 'Se atender: mostrar print/vídeo do sócio usando o Fyness', done: false },
      { text: 'Se NÃO atender: WhatsApp com print do Story do sócio', done: false },
      { text: 'Registrar no CRM: D3 Conteúdo — ligação ou WhatsApp', done: false },
    ],
    inputs: 'Lead sem resposta D1, case de sucesso do mesmo ramo',
    outputs: 'Ligação realizada ou case social enviado via WhatsApp',
    toolsResources: 'Telefone, WhatsApp, Banco de cases, CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Vendedor fez tentativa de ligação no D3. Case por telefone ou WhatsApp.',
  },
  {
    elementId: 'Task_Cont_D7_Breakup',
    elementType: 'sendTask',
    title: 'D7 — Break-up / Último Contato (Vendedor)',
    objective: 'Vendedor encerra ciclo profissionalmente. Sócio NÃO participa do break-up.',
    description: 'Dia 7: Vendedor envia mensagem de encerramento elegante. Psicologia: aversão à perda + profissionalismo. Muitos respondem DEPOIS do break-up.',
    steps: [
      { text: 'Vendedor envia mensagem de encerramento profissional', done: false },
      { text: 'Mencionar que entende que o timing pode não ser ideal', done: false },
      { text: 'Deixar contato do Vendedor salvo como último recurso', done: false },
      { text: 'Registrar no CRM: Break-up Conteúdo enviado pelo Vendedor', done: false },
    ],
    inputs: 'Lead sem resposta há 7 dias',
    outputs: 'Break-up enviado pelo Vendedor, ciclo encerrado',
    toolsResources: 'WhatsApp, CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Vendedor enviou break-up no D7, lead marcado para timer 24h',
  },
  {
    elementId: 'Task_Cont_Nurturing',
    elementType: 'serviceTask',
    title: 'Grupo WhatsApp Nurturing (Conteúdo)',
    objective: 'Manter lead aquecido após responder ao break-up com promoções e cases semanais.',
    description: 'Adicionar lead em grupo WhatsApp para promoções especiais, cases de sucesso semanais e ofertas de reativação.',
    steps: [
      { text: 'Adicionar lead ao grupo de WhatsApp Nurturing', done: false },
      { text: 'Enviar boas-vindas no grupo', done: false },
      { text: 'Configurar cadência semanal de conteúdo', done: false },
      { text: 'Monitorar engajamento no grupo', done: false },
    ],
    inputs: 'Lead respondeu após break-up',
    outputs: 'Lead no grupo de nurturing ativo',
    toolsResources: 'WhatsApp, CRM',
    responsible: 'Automação / Marketing',
    acceptanceCriteria: 'Lead adicionado ao grupo com sucesso',
  },
  {
    elementId: 'Task_Cont_MotivoPerda',
    elementType: 'userTask',
    title: 'CRM — Seleciona Motivo Perda (Conteúdo)',
    objective: 'Registrar motivo da perda para análise de padrões e remarketing futuro.',
    description: 'Selecionar motivo no CRM: Preço, Timing, Concorrente, Não entendeu valor, Ghostou. Registrar para análise.',
    steps: [
      { text: 'Selecionar motivo da perda no CRM', done: false },
      { text: 'Adicionar notas sobre a negociação', done: false },
      { text: 'Marcar lead como LOST', done: false },
      { text: 'Incluir em lista de remarketing se aplicável', done: false },
    ],
    inputs: 'Lead não respondeu após 24h do break-up',
    outputs: 'Motivo registrado, lead marcado como perdido',
    toolsResources: 'CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Motivo de perda registrado no CRM',
  },

  // ═══════════════════════════ POOL: PROSPECÇÃO ATIVA ═══════════════════════════
  {
    elementId: 'Task_Prosp_CriacaoLista',
    elementType: 'serviceTask',
    title: '[AUTOMAÇÃO] Geração de Lista de Leads (Prospecção)',
    objective: 'Gerar automaticamente lista semanal de leads ME/EPP pra prospecção.',
    description: 'Sistema coleta CNPJs via CNAE, Junta Comercial e Google Maps. Enriquece com nome do decisor + telefone + WhatsApp. Entrega lista pronta no CRM todo domingo à noite.',
    steps: [
      { text: 'Scraping automático: CNAE por segmento compatível com Fyness', done: false },
      { text: 'Junta Comercial: empresas abertas nos últimos 90 dias', done: false },
      { text: 'Google Maps: scraping por segmento + cidade', done: false },
      { text: 'Enriquecimento: nome do decisor, telefone, WhatsApp', done: false },
      { text: 'Filtrar: ME/EPP, segmento compatível, remover duplicatas e já contatados', done: false },
      { text: 'Inserir no CRM com formato padrão (Nome, Empresa, CNPJ, Segmento, Telefone, Fonte)', done: false },
      { text: 'Vendedor revisa e prioriza na segunda (5-10 min)', done: false },
    ],
    inputs: 'APIs: Receita Federal/CNAE, Junta Comercial, Google Maps, base de já contatados',
    outputs: 'Lista de leads ME/EPP no CRM pronta pra segunda-feira',
    toolsResources: 'APIs de scraping, CRM, sistema de enriquecimento de dados',
    responsible: 'Automação',
    acceptanceCriteria: 'Lista entregue no CRM domingo à noite, sem duplicatas, com telefone válido',
  },
  {
    elementId: 'Task_Prosp_DM_Auto',
    elementType: 'userTask',
    title: 'Cold Call D0 — 3 Tentativas + WhatsApp Automático (Prospecção)',
    objective: 'Primeiro contato por LIGAÇÃO com 3 tentativas no dia. Abrir com DOR, não apresentação.',
    description: '3 tentativas em horários diferentes (manhã/almoço/tarde). WhatsApp automático só após 3ª tentativa sem resposta. Pesquisar empresa 2 min antes de ligar.',
    steps: [
      { text: 'Pesquisar empresa no Google (CNPJ, segmento, tamanho) — 2 min', done: false },
      { text: 'Preparar case do MESMO RAMO com valor em R$', done: false },
      { text: 'TENTATIVA 1 (manhã 09h-11h): ligar com script de DOR', done: false },
      { text: 'Se não atendeu: NÃO mandar WhatsApp ainda', done: false },
      { text: 'TENTATIVA 2 (2h depois): ligar novamente — horário diferente', done: false },
      { text: 'TENTATIVA 3 (tarde 14h-16h): última tentativa do dia', done: false },
      { text: 'Se não atendeu 3x: CRM dispara WhatsApp automático com dor em R$', done: false },
      { text: 'Se atendeu: qualificar na mesma ligação', done: false },
      { text: 'Se secretária/funcionário atendeu: perguntar melhor horário do dono', done: false },
      { text: 'Registrar no CRM: nº tentativas + conexão (conversa 30s+)', done: false },
    ],
    inputs: 'Lista automática de leads ME/EPP no CRM',
    outputs: 'Conexão útil realizada ou 3 tentativas registradas + WhatsApp enviado',
    toolsResources: 'Telefone, WhatsApp (automação), CRM, Google (pesquisa empresa)',
    responsible: 'Vendedor',
    acceptanceCriteria: '3 tentativas por lead no D0, em horários diferentes, WhatsApp só após 3ª',
  },
  {
    elementId: 'Task_Prosp_Qualificacao',
    elementType: 'userTask',
    title: 'Qualificação na Ligação — É Dono/Gestor ME/EPP? (Prospecção)',
    objective: 'Qualificar na própria ligação: é decisor? ME/EPP? Usa planilha?',
    description: 'Durante a cold call, confirmar perfil ME/EPP: dono/gestor, 1-50 func, sem sistema robusto. Se desqualificado mas receptivo, adicionar ao nurturing.',
    steps: [
      { text: 'Confirmar se é dono/sócio/gestor', done: false },
      { text: 'Perguntar tamanho (1-50 func = ME/EPP)', done: false },
      { text: 'Mapear como controla financeiro (planilha/caderno/nada)', done: false },
      { text: 'Se qualificado: avançar para demo na mesma call ou agendar', done: false },
      { text: 'Se desqualificado: registrar + nurturing se receptivo', done: false },
    ],
    inputs: 'Lead atendeu a cold call',
    outputs: 'Lead qualificado ou descartado com ação no CRM',
    toolsResources: 'Telefone, CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Lead qualificado como ME/EPP decisor com dor mapeada',
  },
  {
    elementId: 'Task_Prosp_Demo',
    elementType: 'userTask',
    title: 'Demo Automática por Setor + Ligação de Fechamento (Prospecção)',
    objective: 'Automação envia demo gravada do setor. Vendedor liga pra fechar + contornar objeções.',
    description: 'CRM identifica setor → envia demo gravada automaticamente. Vendedor liga depois: "Viu a demo? O que achou?" Se nicho raro sem demo pronta, vendedor grava e salva no banco.',
    steps: [
      { text: 'CRM identifica setor do lead na qualificação', done: false },
      { text: 'Automação envia demo gravada do setor + print WhatsApp', done: false },
      { text: 'Se nicho sem demo pronta: vendedor grava áudio 40s + print', done: false },
      { text: 'Vendedor liga: "Viu a demo que mandei? O que achou?"', done: false },
      { text: 'Se "tá caro": reframe pra custo do problema (R$ 800/mês > R$ 137 anual)', done: false },
      { text: 'Se "preciso pensar": eliminar risco — trial grátis sem cartão', done: false },
      { text: 'Se "já uso planilha": dor futura — planilha não avisa nota errada', done: false },
      { text: 'Se "já uso Conta Azul": diferencial áudio 10s vs digitar tudo', done: false },
      { text: 'REGRA: Nunca rebater — CONCORDAR primeiro, depois reframe', done: false },
      { text: 'Fechar: "Quer testar 7 dias grátis? Libero agora."', done: false },
      { text: 'Bônus Educação: "Assinando, você ganha acesso à Plataforma de Educação — cursos, comunidade, mentorias. Tudo de bônus."', done: false },
    ],
    inputs: 'Lead qualificado ME/EPP, setor identificado',
    outputs: 'Demo enviada (automática ou manual), objeção contornada ou callback',
    toolsResources: 'Banco de demos gravadas, WhatsApp, Telefone, CRM',
    responsible: 'Automação + Vendedor (fechamento)',
    acceptanceCriteria: 'Demo do setor enviada e vendedor ligou pra fechar',
  },
  {
    elementId: 'Task_Prosp_D1',
    elementType: 'userTask',
    title: 'D1 — WhatsApp de Valor + Ligação se Reagiu (Prospecção)',
    objective: 'Escalar canal: WhatsApp com dado útil primeiro. Ligação SÓ se lead reagiu (respondeu ou visualizou).',
    description: 'Dia 1 (24h após D0): Não atendeu 3 ligações = provavelmente não viu. Mudar pra WhatsApp com conteúdo de valor. Ligar só se reagiu. Máximo 1 ligação no D1.',
    steps: [
      { text: 'CRM dispara WhatsApp de VALOR com dado do ramo + print (automação, manhã)', done: false },
      { text: 'Se lead RESPONDEU WhatsApp → vendedor liga em < 5 min', done: false },
      { text: 'Se lead VISUALIZOU mas não respondeu → vendedor liga 1x à tarde', done: false },
      { text: 'Se lead NEM VISUALIZOU → NÃO ligar, esperar D3', done: false },
      { text: 'Se atendeu ligação → empurrar pra demo + Manual de Objeções', done: false },
      { text: 'Se pediu callback → agendar no CRM com data/hora', done: false },
      { text: 'Registrar no CRM: WhatsApp enviado + visualizou? + ligação feita?', done: false },
    ],
    inputs: 'Lead não atendeu 3 ligações no D0',
    outputs: 'WhatsApp de valor enviado + ligação se reagiu',
    toolsResources: 'WhatsApp (automação), Telefone, Banco de prints, CRM',
    responsible: 'Automação + Vendedor (se reagiu)',
    acceptanceCriteria: 'WhatsApp de valor enviado, ligação só se lead reagiu (máx 1)',
  },
  {
    elementId: 'Task_Prosp_D3',
    elementType: 'userTask',
    title: 'D3 — Áudio Pessoal + Case do Ramo (Prospecção)',
    objective: 'Escalar pra áudio pessoal: vendedor grava áudio 20-30s com case do MESMO RAMO. Ligação só se reagiu.',
    description: 'Dia 3 (72h após D0): Não reagiu a ligações nem WhatsApp texto. Escalar pra ÁUDIO pessoal (3x mais resposta que texto). Case obrigatório do mesmo ramo com R$. Máximo 1 ligação.',
    steps: [
      { text: 'Vendedor grava ÁUDIO pessoal 20-30s com case do MESMO RAMO + R$', done: false },
      { text: 'Enviar áudio + PRINT do case (antes/depois) no WhatsApp', done: false },
      { text: 'Se lead RESPONDEU (texto ou áudio) → vendedor liga em < 5 min', done: false },
      { text: 'Se lead VISUALIZOU o áudio → vendedor liga 1x à tarde', done: false },
      { text: 'Se lead NEM VISUALIZOU → NÃO ligar, esperar D7', done: false },
      { text: 'Se 0 visualizações até aqui → verificar se WhatsApp é válido no CRM', done: false },
      { text: 'Registrar no CRM: áudio enviado + visualizou? + ligação feita?', done: false },
    ],
    inputs: 'Lead não reagiu ao WhatsApp de valor do D1',
    outputs: 'Áudio pessoal + case enviado + ligação se reagiu',
    toolsResources: 'WhatsApp, Telefone, Banco de cases por ramo, CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Áudio pessoal gravado e enviado, case do mesmo ramo, ligação só se reagiu',
  },
  {
    elementId: 'Task_Prosp_D6',
    elementType: 'userTask',
    title: 'D7 — Escassez + Última Ligação (Prospecção)',
    objective: 'WhatsApp de escassez + 1 última ligação. Última tentativa antes do break-up D14.',
    description: 'Dia 7: Lead recebeu 3 ligações (D0) + WhatsApp valor (D1) + áudio pessoal (D3). Última chance: WhatsApp escassez + 1 ligação final. Após D7 sem resposta → break-up D14.',
    steps: [
      { text: 'CRM dispara WhatsApp de ESCASSEZ: "últimas vagas do trial gratuito" (manhã)', done: false },
      { text: 'Vendedor faz 1 ÚLTIMA ligação à tarde (independente de reação)', done: false },
      { text: 'Se atendeu → fechar trial NA HORA', done: false },
      { text: 'Se pediu callback → agendar no CRM (é a ÚLTIMA CHANCE)', done: false },
      { text: 'Se não atendeu → lead vai pro break-up automático D14', done: false },
      { text: 'Registrar no CRM: D7 resultado + resumo completo da cadência', done: false },
    ],
    inputs: 'Lead não reagiu ao áudio pessoal do D3',
    outputs: 'WhatsApp escassez + última ligação realizada',
    toolsResources: 'WhatsApp (automação), Telefone, CRM',
    responsible: 'Automação + Vendedor (1 ligação)',
    acceptanceCriteria: 'WhatsApp escassez enviado + 1 ligação final feita',
  },
  {
    elementId: 'Task_Prosp_D10_Breakup',
    elementType: 'sendTask',
    title: 'D14 — Break-up Automático + D21 Reabordagem (Prospecção)',
    objective: 'CRM dispara break-up D14 + reabordagem D21. Vendedor não age — automação total.',
    description: 'Após ~6 ligações + 4 WhatsApps + 1 áudio em 7 dias sem resposta. D14: break-up respeitoso. D21: última mensagem. Se responder → vendedor retoma. Se não → nurturing.',
    steps: [
      { text: 'D14: CRM dispara WhatsApp break-up automático (tom leve)', done: false },
      { text: 'D21: CRM dispara última reabordagem automática', done: false },
      { text: 'Se lead responder → vendedor retoma manualmente', done: false },
      { text: 'Se não responder D21 → lead vai pro grupo nurturing automático', done: false },
      { text: 'CRM: Tag [BREAKUP_PROSP] + total de tentativas registrado', done: false },
    ],
    inputs: 'Lead sem resposta após cadência completa (~6 ligações + 4 WhatsApps + 1 áudio)',
    outputs: 'Break-up enviado, lead encerrado ou no nurturing',
    toolsResources: 'WhatsApp (automação), CRM',
    responsible: 'Automação',
    acceptanceCriteria: 'Break-up D14 + reabordagem D21 enviados automaticamente',
  },
  {
    elementId: 'Task_Prosp_Nurturing',
    elementType: 'serviceTask',
    title: 'Grupo WhatsApp Nurturing (Prospecção)',
    objective: 'Manter lead aquecido em grupo de nurturing com cases e promoções.',
    description: 'Adicionar lead em grupo WhatsApp para promoções e cases semanais. Perdido apenas se bloquear/sair.',
    steps: [
      { text: 'Adicionar lead ao grupo Nurturing', done: false },
      { text: 'Enviar boas-vindas', done: false },
      { text: 'Monitorar engajamento', done: false },
    ],
    inputs: 'Lead respondeu ao break-up',
    outputs: 'Lead no grupo de nurturing',
    toolsResources: 'WhatsApp, CRM',
    responsible: 'Automação / Marketing',
    acceptanceCriteria: 'Lead adicionado ao grupo',
  },
  {
    elementId: 'Task_Prosp_MotivoPerda',
    elementType: 'userTask',
    title: 'CRM — Seleciona Motivo Perda (Prospecção)',
    objective: 'Registrar motivo da perda para análise e remarketing.',
    description: 'Selecionar motivo: Preço, Timing, Concorrente, Não entendeu valor, Ghostou. Registrar no CRM.',
    steps: [
      { text: 'Selecionar motivo da perda', done: false },
      { text: 'Adicionar notas', done: false },
      { text: 'Marcar como LOST', done: false },
    ],
    inputs: 'Lead não respondeu 24h após break-up',
    outputs: 'Motivo registrado',
    toolsResources: 'CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Motivo de perda registrado',
  },

  // ═══════════════════════════ POOL: GOOGLE ADS ═══════════════════════════
  {
    elementId: 'Task_ClickWhatsApp',
    elementType: 'userTask',
    title: 'Clica WhatsApp (Google Ads)',
    objective: 'Capturar lead que clicou no botão WhatsApp do anúncio Google.',
    description: 'Lead vem do anúncio Google e clica no WhatsApp. Início do fluxo de atendimento humano.',
    steps: [
      { text: 'Lead clica no botão WhatsApp do anúncio', done: false },
      { text: 'Sistema registra origem Google Ads', done: false },
      { text: 'Encaminhar para Speed to Lead', done: false },
    ],
    inputs: 'Clique no anúncio Google',
    outputs: 'Lead no WhatsApp aguardando atendimento',
    toolsResources: 'Google Ads, WhatsApp',
    responsible: 'Automação',
    acceptanceCriteria: 'Lead capturado com origem rastreada',
  },
  {
    elementId: 'Task_SpeedToLead_Google',
    elementType: 'userTask',
    title: 'Speed to Lead — Resposta < 5 min (Google)',
    objective: 'Responder lead em menos de 5 minutos — cada minuto de atraso reduz 80% a conversão.',
    description: 'Lead quente de Google Ads precisa de resposta IMEDIATA. SLA: < 5 minutos.',
    steps: [
      { text: 'Receber notificação de novo lead Google', done: false },
      { text: 'Responder em < 5 minutos', done: false },
      { text: 'Usar script de abertura Google', done: false },
      { text: 'Direcionar para Flash Demo', done: false },
    ],
    inputs: 'Lead WhatsApp de Google Ads',
    outputs: 'Primeiro contato realizado em < 5 min',
    toolsResources: 'WhatsApp, CRM, Sistema de alertas',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Resposta em < 5 minutos do primeiro contato',
  },
  {
    elementId: 'Task_AlertaHumano_Google',
    elementType: 'userTask',
    title: 'Alerta Humano — Ligar AGORA (Google)',
    objective: 'Ativar vendedor imediatamente para lead quente de Google Ads.',
    description: 'Alerta no sistema para vendedor ligar imediatamente. Lead quente de Google = prioridade máxima.',
    steps: [
      { text: 'Sistema dispara alerta sonoro/push para vendedor', done: false },
      { text: 'Vendedor aceita o lead', done: false },
      { text: 'Ligar imediatamente ou responder WhatsApp', done: false },
    ],
    inputs: 'Novo lead Google Ads',
    outputs: 'Vendedor ativado e em contato',
    toolsResources: 'Sistema de alertas, Telefone, WhatsApp',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Vendedor acionado em < 2 minutos',
  },
  {
    elementId: 'Task_FlashDemo_Google',
    elementType: 'userTask',
    title: 'Flash Demo — Áudio + Print (Google)',
    objective: 'Demonstrar produto rapidamente para lead quente de Google.',
    description: 'Enviar áudio de 20-30s + print do dashboard. Lead de Google busca solução ativa, então mostrar resultado imediato.',
    steps: [
      { text: 'Gravar áudio de 20-30s com demonstração', done: false },
      { text: 'Capturar print de resultado no dashboard', done: false },
      { text: 'Enviar via WhatsApp', done: false },
      { text: 'Fechar com proposta de trial ou assinatura', done: false },
      { text: 'Bônus Educação: "Assinando, você ganha acesso à Plataforma de Educação — cursos, comunidade, mentorias. Tudo de bônus."', done: false },
    ],
    inputs: 'Lead engajado na conversa',
    outputs: 'Demo enviada, proposta feita',
    toolsResources: 'WhatsApp, Gravação de tela, Fyness',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Demo enviada com proposta clara',
  },
  {
    elementId: 'Task_OfertaTrial_Google',
    elementType: 'userTask',
    title: 'Oferta Trial 7 Dias (Google)',
    objective: 'Converter interesse em trial gratuito de 7 dias.',
    description: 'Oferecer trial de 7 dias para lead que demonstrou interesse mas não fechou na hora.',
    steps: [
      { text: 'Apresentar benefícios do trial', done: false },
      { text: 'Enviar link de cadastro trial', done: false },
      { text: 'Confirmar ativação do trial', done: false },
    ],
    inputs: 'Lead interessado mas não fechou',
    outputs: 'Trial ativado',
    toolsResources: 'WhatsApp, Fyness, CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Trial ativado e configuração inicial feita',
  },
  {
    elementId: 'Task_ClickCheckout_Self',
    elementType: 'userTask',
    title: 'Clica "Testar Agora/Assinar" (Self-Service)',
    objective: 'Capturar lead que optou por self-service no checkout.',
    description: 'Lead clica no botão de self-service. Fluxo automático sem vendedor.',
    steps: [
      { text: 'Lead clica em "Testar Agora" ou "Assinar"', done: false },
      { text: 'Redirecionar para página de checkout', done: false },
    ],
    inputs: 'Clique no CTA do site',
    outputs: 'Lead na página de checkout',
    toolsResources: 'Site, Gateway de pagamento',
    responsible: 'Automação',
    acceptanceCriteria: 'Lead chegou na página de checkout',
  },
  {
    elementId: 'Task_PreencheDados_Self',
    elementType: 'userTask',
    title: 'Preenche Dados + Cartão (Self-Service)',
    objective: 'Lead preenche formulário. Se abandonar com dados parciais, disparar recuperação.',
    description: 'Formulário de checkout com monitoramento de abandono. Se preencheu e-mail/telefone mas não pagou: pop-up 2min, WhatsApp 10min, ligação 1h, e-mail 24h.',
    steps: [
      { text: 'Lead preenche nome, e-mail, empresa', done: false },
      { text: 'Adiciona dados do cartão', done: false },
      { text: 'Confirma a assinatura', done: false },
      { text: 'SE ABANDONOU: pop-up 2 min "Precisa de ajuda?"', done: false },
      { text: 'SE ABANDONOU: WhatsApp automático em 10 min', done: false },
      { text: 'SE ABANDONOU: vendedor liga em 1h (se telefone preenchido)', done: false },
    ],
    inputs: 'Dados do lead',
    outputs: 'Cadastro completo OU lead capturado para recuperação',
    toolsResources: 'Gateway de pagamento, CRM, WhatsApp API',
    responsible: 'Automação + Vendedor (se abandono)',
    acceptanceCriteria: 'Pagamento aprovado OU recuperação acionada em caso de abandono',
  },
  {
    elementId: 'Task_AutomacaoBoasVindas',
    elementType: 'serviceTask',
    title: 'Automação D0 — Boas-vindas (Google)',
    objective: 'Enviar boas-vindas automática após checkout com guia de início rápido.',
    description: 'Sequência automática: e-mail de boas-vindas + WhatsApp com link de acesso + vídeo de configuração.',
    steps: [
      { text: 'Enviar e-mail de boas-vindas com link de acesso', done: false },
      { text: 'Enviar WhatsApp com vídeo de configuração rápida', done: false },
      { text: 'Registrar início do onboarding no CRM', done: false },
    ],
    inputs: 'Pagamento confirmado',
    outputs: 'Boas-vindas enviadas, onboarding iniciado',
    toolsResources: 'E-mail marketing, WhatsApp API, CRM',
    responsible: 'Automação',
    acceptanceCriteria: 'E-mail e WhatsApp de boas-vindas entregues',
  },
  {
    elementId: 'Task_RecuperacaoCarrinho',
    elementType: 'serviceTask',
    title: 'Recuperação de Carrinho (10 min)',
    objective: 'Recuperar leads que abandonaram o checkout antes de finalizar.',
    description: 'Automação 10 min após abandono: WhatsApp + e-mail oferecendo ajuda para completar o cadastro.',
    steps: [
      { text: 'Detectar abandono de carrinho (10 min sem completar)', done: false },
      { text: 'Enviar WhatsApp: "Vi que você não completou..."', done: false },
      { text: 'Enviar e-mail de recuperação', done: false },
      { text: 'Escalar para vendedor se não retornar em 1h', done: false },
    ],
    inputs: 'Checkout abandonado há 10 min',
    outputs: 'Mensagem de recuperação enviada',
    toolsResources: 'WhatsApp API, E-mail marketing, CRM',
    responsible: 'Automação',
    acceptanceCriteria: 'Mensagem enviada em 10 min do abandono',
  },
  {
    elementId: 'Task_D1_WhatsApp3_Diferenca_Google',
    elementType: 'sendTask',
    title: 'D1 — WhatsApp 3 (Manhã) — A Diferença (Google)',
    objective: 'Diferenciar Fyness de planilhas e concorrentes no D1.',
    description: 'Dia 1 manhã: mensagem mostrando a diferença real entre usar e não usar o Fyness.',
    steps: [
      { text: 'Enviar mensagem com comparação visual', done: false },
      { text: 'Mostrar antes/depois de um cliente real', done: false },
      { text: 'Registrar no CRM: D1 Google enviado', done: false },
    ],
    inputs: 'Lead não fechou na demo',
    outputs: 'Mensagem de diferenciação enviada',
    toolsResources: 'WhatsApp, Banco de comparações, CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Mensagem enviada no D1 manhã',
  },
  {
    elementId: 'Task_D1_Ligacao2_Google',
    elementType: 'userTask',
    title: 'D1 — Ligação 2 (Tarde) (Google)',
    objective: 'Segunda tentativa de contato telefônico para leads quentes de Google.',
    description: 'Dia 1 tarde: ligar novamente para reforçar interesse e tirar dúvidas.',
    steps: [
      { text: 'Ligar no D1 à tarde', done: false },
      { text: 'Reforçar benefícios discutidos', done: false },
      { text: 'Tirar dúvidas pendentes', done: false },
      { text: 'Registrar resultado no CRM', done: false },
    ],
    inputs: 'Lead não fechou na primeira abordagem',
    outputs: 'Segunda ligação realizada',
    toolsResources: 'Telefone, CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Ligação realizada no D1 tarde',
  },
  {
    elementId: 'Task_D3_WhatsApp4_Case_Google',
    elementType: 'sendTask',
    title: 'D3 — WhatsApp 4 — Cobrança Social (Google)',
    objective: 'Usar prova social com case de cliente do mesmo ramo.',
    description: 'Dia 3: enviar case de sucesso com dados reais. Cobrança social sutil.',
    steps: [
      { text: 'Selecionar case do mesmo ramo do lead', done: false },
      { text: 'Enviar com dados concretos de resultado', done: false },
      { text: 'Registrar no CRM: D3 Google enviado', done: false },
    ],
    inputs: 'Lead sem resposta D1',
    outputs: 'Case social enviado',
    toolsResources: 'WhatsApp, Banco de cases, CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Case enviado no D3',
  },
  {
    elementId: 'Task_D5_Ligacao3_Google',
    elementType: 'userTask',
    title: 'D5 — Ligação 3 (Última Tentativa) (Google)',
    objective: 'Última tentativa de contato telefônico antes do break-up.',
    description: 'Dia 5: ligar uma última vez. Se atender, fazer oferta final.',
    steps: [
      { text: 'Ligar no D5', done: false },
      { text: 'Se atender, fazer oferta especial', done: false },
      { text: 'Se não atender, seguir para WhatsApp D5', done: false },
      { text: 'Registrar resultado no CRM', done: false },
    ],
    inputs: 'Lead sem conversão D3',
    outputs: 'Última tentativa telefônica realizada',
    toolsResources: 'Telefone, CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Ligação realizada no D5',
  },
  {
    elementId: 'Task_D5_WhatsApp5_Pressao_Google',
    elementType: 'sendTask',
    title: 'D5 — WhatsApp 5 — A Pressão (Google)',
    objective: 'Aplicar pressão com escassez e urgência.',
    description: 'Dia 5: mensagem de pressão com oferta limitada.',
    steps: [
      { text: 'Enviar mensagem de escassez', done: false },
      { text: 'Mencionar vagas limitadas ou condição expirando', done: false },
      { text: 'Registrar no CRM: D5 Google enviado', done: false },
    ],
    inputs: 'Lead sem resposta D3',
    outputs: 'Mensagem de pressão enviada',
    toolsResources: 'WhatsApp, CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Mensagem de pressão enviada no D5',
  },
  {
    elementId: 'Task_D7_Fechamento_Google',
    elementType: 'userTask',
    title: 'D7 — Fechamento (Escada Downsell) (Google)',
    objective: 'Última chance de fechar com escada de downsell: plano premium → básico → trial.',
    description: 'Dia 7: se ainda há algum interesse, fazer escada de downsell para não perder totalmente.',
    steps: [
      { text: 'Oferecer plano premium com desconto', done: false },
      { text: 'Se recusar, oferecer plano básico', done: false },
      { text: 'Se recusar, oferecer trial gratuito', done: false },
      { text: 'Registrar resultado final no CRM', done: false },
    ],
    inputs: 'Lead ainda com algum engajamento',
    outputs: 'Proposta final feita com downsell',
    toolsResources: 'WhatsApp, CRM, Tabela de preços',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Todas as opções da escada ofertadas',
  },
  {
    elementId: 'Task_D7_WhatsApp6_Breakup_Google',
    elementType: 'sendTask',
    title: 'D7 — WhatsApp 6 — Break-up Ultimato (Google)',
    objective: 'Break-up final para leads de Google que não converteram.',
    description: 'Dia 7: ultimato elegante. Encerrar ciclo profissionalmente com porta aberta.',
    steps: [
      { text: 'Enviar mensagem de encerramento profissional', done: false },
      { text: 'Deixar contato salvo', done: false },
      { text: 'Registrar no CRM: Break-up Google', done: false },
    ],
    inputs: 'Lead sem conversão após 7 dias',
    outputs: 'Break-up enviado',
    toolsResources: 'WhatsApp, CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Break-up enviado no D7',
  },
  {
    elementId: 'Task_SelecaoMotivo_Google',
    elementType: 'userTask',
    title: 'CRM — Selecionar Motivo da Perda (Google)',
    objective: 'Registrar motivo da perda de lead Google para otimizar campanhas.',
    description: 'Motivos: Ghosting, Preço, Concorrência, Desqualificado, Timing, Outro. Dados para otimizar Google Ads.',
    steps: [
      { text: 'Selecionar motivo no CRM', done: false },
      { text: 'Adicionar notas de contexto', done: false },
      { text: 'Marcar como LOST com tag [GOOGLE_ADS]', done: false },
    ],
    inputs: 'Lead perdido',
    outputs: 'Motivo registrado para análise',
    toolsResources: 'CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Motivo registrado com tag de origem',
  },
  {
    elementId: 'Task_GrupoNurturing_Google',
    elementType: 'serviceTask',
    title: 'Grupo Promoções + Remarketing (Google)',
    objective: 'Manter lead de Google aquecido para remarketing e promoções futuras.',
    description: 'Adicionar em grupo WhatsApp de promoções e remarketing Google Ads.',
    steps: [
      { text: 'Adicionar ao grupo de promoções', done: false },
      { text: 'Incluir em lista de remarketing Google Ads', done: false },
      { text: 'Monitorar reengajamento', done: false },
    ],
    inputs: 'Lead respondeu ao break-up mas não converteu',
    outputs: 'Lead em nurturing + remarketing',
    toolsResources: 'WhatsApp, Google Ads Remarketing, CRM',
    responsible: 'Automação / Marketing',
    acceptanceCriteria: 'Lead no grupo e na lista de remarketing',
  },

  // ═══════════════════════════ POOL: META ADS ═══════════════════════════
  {
    elementId: 'Task_PaginaFiltro_Meta',
    elementType: 'userTask',
    title: 'Página de Captura (Meta Ads)',
    objective: 'Capturar contato qualificado via landing page antes da abordagem.',
    description: 'Landing page: "Transforme áudios em organização financeira". Filtro de qualificação: "Você é dono/gestor?". Formulário: Nome, WhatsApp, Segmento.',
    steps: [
      { text: 'Lead clica no anúncio Meta', done: false },
      { text: 'Preenche landing page com Nome, WhatsApp, Segmento', done: false },
      { text: 'Responde filtro: "Você é dono/gestor?"', done: false },
      { text: 'Sistema registra lead qualificado no CRM', done: false },
    ],
    inputs: 'Clique no anúncio Meta',
    outputs: 'Lead qualificado com WhatsApp',
    toolsResources: 'Landing page, Meta Ads, CRM',
    responsible: 'Automação / Marketing',
    acceptanceCriteria: 'Lead capturado com WhatsApp e qualificação',
  },
  {
    elementId: 'Task_WhatsApp_D0_Meta',
    elementType: 'sendTask',
    title: 'D0 — WhatsApp (Min 0-5) — Abordagem Ativa (Meta)',
    objective: 'Quebra de gelo rápida e confirmação de interesse real em < 5 min.',
    description: 'Speed to Lead Meta: mensagem imediata confirmando o preenchimento do formulário e o segmento.',
    steps: [
      { text: 'Enviar mensagem em < 5 min após cadastro', done: false },
      { text: 'Confirmar segmento do lead', done: false },
      { text: 'Quebrar o gelo com pergunta casual', done: false },
      { text: 'Registrar primeiro contato no CRM', done: false },
    ],
    inputs: 'Lead preencheu landing page',
    outputs: 'Primeiro contato realizado',
    toolsResources: 'WhatsApp, CRM',
    responsible: 'Vendedor / Automação',
    acceptanceCriteria: 'Resposta enviada em < 5 min',
  },
  {
    elementId: 'Task_FlashDemo_D0_Meta',
    elementType: 'sendTask',
    title: 'D0 — Flash Demo — Áudio + Print (Meta)',
    objective: 'Mostrar produto funcionando antes de qualquer pitch.',
    description: 'Flash Demo: áudio de 20s mostrando como manda áudio e a IA organiza + print de resultado. Perguntar se já viu algo parecido.',
    steps: [
      { text: 'Gravar áudio de 20s demonstrando o produto', done: false },
      { text: 'Capturar print do resultado', done: false },
      { text: 'Enviar áudio + print', done: false },
      { text: 'Perguntar: "Testou algo parecido antes?"', done: false },
      { text: 'Bônus Educação: "Assinando, você ganha acesso à Plataforma de Educação — cursos, comunidade, mentorias. Tudo de bônus."', done: false },
    ],
    inputs: 'Lead respondeu a abordagem inicial',
    outputs: 'Demo enviada, interesse medido',
    toolsResources: 'WhatsApp, Gravação de tela, Fyness',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Demo enviada com resposta do lead',
  },
  {
    elementId: 'Task_Meta_D1_Reapproach',
    elementType: 'userTask',
    title: 'D1 — Ligação + Reabordagem (Meta)',
    objective: 'Ligar primeiro para reengajar. Ligação D1 resgata leads que só precisam de um empurrão.',
    description: 'Dia 1: LIGAR contando case de cliente do nicho. Se não atender, enviar WhatsApp com link de vídeo case.',
    steps: [
      { text: 'LIGAR para o lead (prioridade #1)', done: false },
      { text: 'Se atender: contar case + reengajar com demonstração', done: false },
      { text: 'Se NÃO atender: enviar WhatsApp com vídeo case do nicho', done: false },
      { text: 'Registrar no CRM: D1 Meta — ligação ou WhatsApp', done: false },
    ],
    inputs: 'Lead não se interessou no D0',
    outputs: 'Ligação realizada ou conteúdo educativo enviado',
    toolsResources: 'Telefone, WhatsApp, Banco de vídeos de cases, CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Tentativa de ligação feita no D1',
  },
  {
    elementId: 'Task_Meta_D3',
    elementType: 'userTask',
    title: 'D3 — Ligação + Case do Nicho (Meta)',
    objective: 'Ligar referenciando o anúncio Meta como ponto de conexão. Lead já preencheu formulário.',
    description: 'Dia 3: LIGAR conectando o anúncio com case real. "Você preencheu nosso formulário → outro cliente do seu ramo também veio pelo anúncio e organizou tudo em 14 dias." Se não atender, WhatsApp com print.',
    steps: [
      { text: 'LIGAR referenciando o formulário que o lead preencheu', done: false },
      { text: 'Se atender: conectar com case de alguém que veio pelo mesmo anúncio', done: false },
      { text: 'Se NÃO atender: WhatsApp com print do dashboard do case', done: false },
      { text: 'Registrar no CRM: D3 Meta — ligação ou WhatsApp', done: false },
    ],
    inputs: 'Lead não respondeu D1',
    outputs: 'Ligação realizada ou case social enviado',
    toolsResources: 'Telefone, WhatsApp, Banco de cases, CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Tentativa de ligação feita no D3',
  },
  {
    elementId: 'Task_Meta_D7',
    elementType: 'userTask',
    title: 'D7 — Ligação + Ultimato (Meta)',
    objective: 'Lead de Meta já viu anúncio + demo + case. Falta empurrão final. Referenciar que ele já conhece o produto.',
    description: 'Dia 7: LIGAR reforçando que ele JÁ VIU o sistema e reduzindo atrito. Se não atender, WhatsApp curto de escassez.',
    steps: [
      { text: 'LIGAR reforçando: "Sei que você já viu como funciona"', done: false },
      { text: 'Se atender: fechar trial na hora sem re-explicar produto', done: false },
      { text: 'Se NÃO atender: WhatsApp "Já viu o sistema. Últimas vagas."', done: false },
      { text: 'Registrar no CRM: D7 Meta — ligação ou WhatsApp', done: false },
    ],
    inputs: 'Lead sem resposta D3',
    outputs: 'Ligação realizada ou escassez enviada',
    toolsResources: 'Telefone, WhatsApp, CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Tentativa de ligação feita no D7',
  },
  {
    elementId: 'Task_Meta_D10_Breakup',
    elementType: 'sendTask',
    title: 'D10 — Break-up (Meta)',
    objective: 'Encerrar mencionando que ELE clicou no anúncio — gera reflexão/culpa.',
    description: 'Dia 10: break-up com referência ao anúncio Meta. "Sei que você se interessou pelo anúncio..." reforça que a iniciativa foi dele.',
    steps: [
      { text: 'Enviar mensagem referenciando o interesse pelo anúncio', done: false },
      { text: 'Deixar porta aberta para retorno', done: false },
      { text: 'Registrar no CRM: Break-up Meta enviado', done: false },
    ],
    inputs: 'Lead sem resposta há 10 dias',
    outputs: 'Break-up enviado',
    toolsResources: 'WhatsApp, CRM',
    responsible: 'Vendedor / Automação',
    acceptanceCriteria: 'Break-up enviado no D10',
  },
  {
    elementId: 'Task_Meta_Nurturing',
    elementType: 'serviceTask',
    title: 'Grupo WhatsApp Nurturing (Meta)',
    objective: 'Manter lead aquecido em grupo de nurturing com cases e promoções.',
    description: 'Adicionar lead em grupo WhatsApp para promoções e cases semanais.',
    steps: [
      { text: 'Adicionar lead ao grupo Nurturing', done: false },
      { text: 'Enviar boas-vindas', done: false },
      { text: 'Monitorar engajamento', done: false },
    ],
    inputs: 'Lead respondeu ao break-up',
    outputs: 'Lead no grupo de nurturing',
    toolsResources: 'WhatsApp, CRM',
    responsible: 'Automação / Marketing',
    acceptanceCriteria: 'Lead adicionado ao grupo',
  },
  {
    elementId: 'Task_Meta_MotivoPerda',
    elementType: 'userTask',
    title: 'CRM — Seleciona Motivo Perda (Meta)',
    objective: 'Registrar motivo da perda com tag [META_ADS] para otimizar campanhas.',
    description: 'Motivos: Preço, Timing, Concorrente, Não entendeu valor, Ghostou, Clicou sem intenção. Se "Clicou sem intenção" for frequente → revisar segmentação.',
    steps: [
      { text: 'Selecionar motivo no CRM (inclui "Clicou sem intenção")', done: false },
      { text: 'Adicionar ID da campanha Meta Ads', done: false },
      { text: 'Marcar como LOST com tag [META_ADS]', done: false },
      { text: 'Se motivo "Clicou sem intenção" → alertar equipe de tráfego', done: false },
    ],
    inputs: 'Lead não respondeu 24h após break-up',
    outputs: 'Motivo registrado',
    toolsResources: 'CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Motivo registrado com tag de origem',
  },

  // ═══════════════════════════ POOL: TRIAL ═══════════════════════════
  {
    elementId: 'Task_Trial_D0_BoasVindas',
    elementType: 'serviceTask',
    title: 'D0 — Boas-vindas + Guia Rápido (Trial)',
    objective: 'Garantir que o lead faça o primeiro lançamento nas primeiras horas.',
    description: 'Onboarding imediato: e-mail/WhatsApp com vídeo de 2 min + guia "3 passos para seu primeiro lançamento" + CTA.',
    steps: [
      { text: 'Enviar e-mail/WhatsApp de boas-vindas com vídeo de 2 min', done: false },
      { text: 'Incluir guia rápido: 3 passos para primeiro lançamento', done: false },
      { text: 'CTA: "Faça seu primeiro lançamento agora"', done: false },
      { text: 'Registrar no CRM: Trial D0 enviado', done: false },
    ],
    inputs: 'Trial ativado',
    outputs: 'Boas-vindas enviadas, guia entregue',
    toolsResources: 'E-mail marketing, WhatsApp API, CRM',
    responsible: 'Automação',
    acceptanceCriteria: 'Boas-vindas entregues no mesmo dia da ativação',
  },
  {
    elementId: 'Task_Trial_D1_Dica',
    elementType: 'sendTask',
    title: 'D1 — Dica Feature-Chave (Trial)',
    objective: 'Mostrar a funcionalidade mais impactante para engajar no D1.',
    description: 'Dia 1 (se usou): enviar dica da feature-chave que mais gera valor para o segmento do lead.',
    steps: [
      { text: 'Identificar feature mais relevante ao segmento', done: false },
      { text: 'Enviar dica com tutorial rápido', done: false },
      { text: 'Registrar engajamento no CRM', done: false },
    ],
    inputs: 'Lead usou o sistema no D0',
    outputs: 'Dica de feature enviada',
    toolsResources: 'WhatsApp, CRM, Analytics Fyness',
    responsible: 'Automação',
    acceptanceCriteria: 'Dica enviada no D1 para leads que usaram',
  },
  {
    elementId: 'Task_Trial_D1_Reengajamento',
    elementType: 'sendTask',
    title: 'D1 — Reengajamento (Não Usou) (Trial)',
    objective: 'Reengajar lead que ativou trial mas não usou no D0.',
    description: 'Dia 1 (se NÃO usou): mensagem de incentivo para fazer o primeiro lançamento.',
    steps: [
      { text: 'Verificar se lead fez algum lançamento no D0', done: false },
      { text: 'Se não usou, enviar mensagem de incentivo', done: false },
      { text: 'Oferecer ajuda para configurar', done: false },
      { text: 'Registrar no CRM: D1 Reengajamento Trial', done: false },
    ],
    inputs: 'Lead ativou trial mas não usou',
    outputs: 'Mensagem de reengajamento enviada',
    toolsResources: 'WhatsApp, CRM, Analytics Fyness',
    responsible: 'Automação',
    acceptanceCriteria: 'Mensagem enviada para leads inativos no D1',
  },
  {
    elementId: 'Task_Trial_D2_Case',
    elementType: 'sendTask',
    title: 'D2 — Case de Sucesso (Trial)',
    objective: 'Reforçar valor com case de cliente que converteu em trial.',
    description: 'Dia 2: case de cliente que começou no trial e hoje é assinante. Mostrar resultado concreto.',
    steps: [
      { text: 'Selecionar case de trial → assinante', done: false },
      { text: 'Enviar com resultado concreto', done: false },
      { text: 'Registrar no CRM: D2 Trial enviado', done: false },
    ],
    inputs: 'Lead em trial D2',
    outputs: 'Case de sucesso enviado',
    toolsResources: 'WhatsApp, Banco de cases, CRM',
    responsible: 'Automação',
    acceptanceCriteria: 'Case enviado no D2',
  },
  {
    elementId: 'Task_Trial_D3_Parabens',
    elementType: 'sendTask',
    title: 'D3 — Parabéns + Próximo Nível (Trial)',
    objective: 'Parabenizar progresso e mostrar próximo nível de uso.',
    description: 'Dia 3 (se usou): parabenizar e mostrar features avançadas como próximo passo.',
    steps: [
      { text: 'Verificar atividade do lead nos últimos 3 dias', done: false },
      { text: 'Enviar parabéns personalizado', done: false },
      { text: 'Mostrar próximo nível de funcionalidades', done: false },
    ],
    inputs: 'Lead ativo no trial D3',
    outputs: 'Parabéns + direcionamento enviado',
    toolsResources: 'WhatsApp, CRM, Analytics',
    responsible: 'Automação',
    acceptanceCriteria: 'Mensagem de parabéns enviada no D3 para ativos',
  },
  {
    elementId: 'Task_Trial_D3_Resgate',
    elementType: 'userTask',
    title: 'D3 — Ligação de Resgate (Trial)',
    objective: 'Ligar para leads que não estão usando o trial para resgatar.',
    description: 'Dia 3 (se NÃO usou): ligação humana para entender por que não está usando e ajudar.',
    steps: [
      { text: 'Verificar que lead não fez lançamentos em 3 dias', done: false },
      { text: 'Ligar para entender o motivo', done: false },
      { text: 'Ajudar a configurar na hora se possível', done: false },
      { text: 'Registrar resultado no CRM', done: false },
    ],
    inputs: 'Lead inativo no trial há 3 dias',
    outputs: 'Contato humano realizado, motivo identificado',
    toolsResources: 'Telefone, CRM, Fyness',
    responsible: 'Vendedor (se inativo)',
    acceptanceCriteria: 'Ligação realizada no D3 para leads inativos',
  },
  {
    elementId: 'Task_Trial_D5_Urgencia',
    elementType: 'userTask',
    title: 'D5 — Ligação + Urgência (Trial)',
    objective: 'Ligar para lead engajado no D5 — faltam 2 dias. Suporte genuíno antes da oferta D6.',
    description: 'Dia 5: LIGAR para o lead. Perguntar sobre dúvidas, ajudar com configuração, mostrar valor. Se não atender, WhatsApp curto de urgência.',
    steps: [
      { text: 'LIGAR para o lead (prioridade #1)', done: false },
      { text: 'Se atender: ajudar com dúvidas + perguntar se quer converter', done: false },
      { text: 'Se NÃO atender: enviar WhatsApp "Faltam 2 dias, precisa de ajuda?"', done: false },
      { text: 'Registrar no CRM: D5 Trial — ligação ou WhatsApp', done: false },
    ],
    inputs: 'Lead no D5 do trial',
    outputs: 'Urgência comunicada + suporte oferecido',
    toolsResources: 'WhatsApp, CRM',
    responsible: 'Automação',
    acceptanceCriteria: 'Mensagem de urgência enviada no D5',
  },
  {
    elementId: 'Task_Trial_D6_Oferta',
    elementType: 'userTask',
    title: 'D6 — Ligação + Oferta de Conversão (Trial)',
    objective: 'Ligar no penúltimo dia com oferta especial. Ligação D6 converte 4x mais que WhatsApp.',
    description: 'Dia 6: LIGAR com oferta Anual 40% OFF + onboarding prioritário. Se não atender, enviar WhatsApp com oferta.',
    steps: [
      { text: 'LIGAR para o lead (prioridade #1)', done: false },
      { text: 'Se atender: apresentar oferta Anual 40% OFF + onboarding', done: false },
      { text: 'Se NÃO atender: WhatsApp com oferta "Anual 40% OFF, bora?"', done: false },
      { text: 'Registrar no CRM: D6 Trial — ligação ou WhatsApp', done: false },
    ],
    inputs: 'Lead no D6 do trial',
    outputs: 'Oferta de conversão enviada',
    toolsResources: 'WhatsApp, CRM, Gateway de pagamento',
    responsible: 'Automação / Vendedor',
    acceptanceCriteria: 'Oferta enviada no D6',
  },
  {
    elementId: 'Task_Trial_Extension',
    elementType: 'serviceTask',
    title: 'Extensão +3 Dias (Reset Trial)',
    objective: 'Dar mais 3 dias para leads que demonstraram interesse mas não converteram.',
    description: 'Extensão automática do trial por +3 dias para leads que tiveram algum engajamento.',
    steps: [
      { text: 'Verificar nível de engajamento durante o trial', done: false },
      { text: 'Se engajou (> 3 lançamentos), estender +3 dias', done: false },
      { text: 'Notificar lead sobre a extensão', done: false },
      { text: 'Registrar no CRM: Trial estendido', done: false },
    ],
    inputs: 'Trial expirado + engajamento mínimo',
    outputs: 'Trial estendido +3 dias',
    toolsResources: 'Fyness, CRM, WhatsApp',
    responsible: 'Automação',
    acceptanceCriteria: 'Trial estendido para leads com engajamento',
  },
  {
    elementId: 'Task_Trial_Breakup',
    elementType: 'userTask',
    title: 'D7 — Resgate Final + Break-up (Trial)',
    objective: 'LIGAR antes do break-up para resgate secundário. WhatsApp break-up só como backup.',
    description: 'Último dia: LIGAR para entender o que faltou. Se preço → 25% OFF. Se timing → extensão. Se não atender → WhatsApp break-up.',
    steps: [
      { text: 'LIGAR para o lead (resgate secundário)', done: false },
      { text: 'Se atender: perguntar o que faltou e oferecer solução', done: false },
      { text: 'Se preço → oferecer 25% OFF na hora', done: false },
      { text: 'Se timing → oferecer extensão +3 dias', done: false },
      { text: 'Se NÃO atender → enviar WhatsApp break-up elegante', done: false },
      { text: 'Registrar no CRM: Trial Break-up + motivo se informado', done: false },
    ],
    inputs: 'Trial expirado sem conversão',
    outputs: 'Resgate por ligação ou break-up por WhatsApp',
    toolsResources: 'Telefone, WhatsApp, CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Tentativa de ligação + break-up enviado',
  },
  {
    elementId: 'Task_Trial_OfertaDesconto',
    elementType: 'sendTask',
    title: 'Oferta 25% OFF (Recuperação por Preço)',
    objective: 'Converter lead que perdeu por preço sem desvalorizar o produto.',
    description: 'Oferta de 25% OFF nos primeiros 3 meses como última tentativa. Máximo 25% para não virar commodity.',
    steps: [
      { text: 'Enviar oferta de 25% OFF nos primeiros 3 meses', done: false },
      { text: 'Prazo limitado: 48h para aproveitar', done: false },
      { text: 'REGRA: nunca oferecer mais que 25% de desconto', done: false },
      { text: 'Registrar no CRM', done: false },
    ],
    inputs: 'Lead que respondeu ao break-up',
    outputs: 'Oferta de desconto enviada',
    toolsResources: 'WhatsApp, CRM, Gateway de pagamento',
    responsible: 'Automação / Vendedor',
    acceptanceCriteria: 'Oferta enviada com prazo de 48h',
  },
  {
    elementId: 'Task_Trial_Nurturing',
    elementType: 'serviceTask',
    title: 'Grupo Nurturing (Trial)',
    objective: 'Manter lead aquecido pós-trial para futura conversão.',
    description: 'Adicionar em grupo de nurturing com cases, promoções e conteúdo.',
    steps: [
      { text: 'Adicionar ao grupo Nurturing', done: false },
      { text: 'Monitorar engajamento', done: false },
    ],
    inputs: 'Lead respondeu ao break-up',
    outputs: 'Lead no grupo de nurturing',
    toolsResources: 'WhatsApp, CRM',
    responsible: 'Automação',
    acceptanceCriteria: 'Lead adicionado ao grupo',
  },
  {
    elementId: 'Task_Trial_MotivoPerda',
    elementType: 'userTask',
    title: 'CRM — Motivo da Perda (Trial)',
    objective: 'Registrar motivo da não-conversão do trial.',
    description: 'Selecionar motivo: Não usou, Preço, Concorrente, Funcionalidade faltante, Outro.',
    steps: [
      { text: 'Selecionar motivo da perda no CRM', done: false },
      { text: 'Adicionar notas sobre o uso durante trial', done: false },
      { text: 'Marcar como LOST com tag [TRIAL]', done: false },
    ],
    inputs: 'Lead não converteu após trial',
    outputs: 'Motivo registrado',
    toolsResources: 'CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Motivo registrado com dados de uso do trial',
  },
  {
    elementId: 'Task_Trial_Lembrete30d',
    elementType: 'serviceTask',
    title: 'CRM — Lembrete 30 Dias (Trial)',
    objective: 'Agendar recontato 30 dias após perda para tentar reativação.',
    description: 'Automação CRM: agendar lembrete para recontatar lead 30 dias depois com nova oferta.',
    steps: [
      { text: 'Registrar lembrete de 30 dias no CRM', done: false },
      { text: 'Preparar oferta de reativação', done: false },
      { text: 'Enviar mensagem no D+30', done: false },
    ],
    inputs: 'Lead perdido marcado no CRM',
    outputs: 'Lembrete agendado, recontato em 30 dias',
    toolsResources: 'CRM, WhatsApp',
    responsible: 'Automação',
    acceptanceCriteria: 'Lembrete criado no CRM para D+30',
  },

  // ═══════════════════════════ POOL: NÚCLEO (CHECKOUT + PAGAMENTO) ═══════════════════════════
  {
    elementId: 'Task_Checkout_Anual',
    elementType: 'task',
    title: 'Checkout — Plano Anual (R$ 1.497)',
    objective: 'Fechar com o plano de maior valor e cashflow antecipado.',
    description: 'Oferta principal: R$ 1.497/ano (R$ 124,75/mês). Parcelamento até 12x. Gateway Hotmart + Asaas como fallback.',
    steps: [
      { text: 'Enviar link de checkout Anual (Hotmart)', done: false },
      { text: 'Confirmar que lead recebeu e acessou o link', done: false },
      { text: 'Acompanhar se pagamento foi aprovado', done: false },
      { text: 'Se falhar → sequência de downsell automático', done: false },
    ],
    inputs: 'Lead qualificado pronto para checkout',
    outputs: 'Pagamento aprovado ou falha detectada',
    toolsResources: 'Hotmart, Asaas, CRM',
    responsible: 'Automação / Vendedor',
    acceptanceCriteria: 'Pagamento processado ou downsell ativado',
  },
  {
    elementId: 'Task_Split_Parceiro',
    elementType: 'task',
    title: 'Split — 30% Comissão Parceiro',
    objective: 'Pagar automaticamente 30% de comissão ao parceiro que indicou.',
    description: 'Split automático via Asaas Split Payments. Parceiro recebe R$ 449,10 (Anual) D+30 após garantia. Apenas para leads com tag [INDICAÇÃO].',
    steps: [
      { text: 'Verificar se lead tem tag [INDICAÇÃO: NOME_DO_PARCEIRO]', done: false },
      { text: 'Configurar split de 30% no gateway (Asaas)', done: false },
      { text: 'Agendar pagamento para D+30 (após garantia)', done: false },
      { text: 'Notificar parceiro sobre comissão agendada', done: false },
    ],
    inputs: 'Pagamento aprovado + tag de indicação',
    outputs: 'Split configurado, parceiro notificado',
    toolsResources: 'Asaas Split Payments, CRM',
    responsible: 'Automação / Financeiro',
    acceptanceCriteria: 'Split configurado e parceiro avisado',
  },
  {
    elementId: 'Task_Onboarding_Pago',
    elementType: 'task',
    title: 'Onboarding — Acesso Imediato',
    objective: 'Garantir que o cliente tenha acesso completo em até 5 minutos após pagamento.',
    description: 'Webhook pós-pagamento: libera acesso, envia e-mail de boas-vindas com credenciais, WhatsApp com link de suporte, adiciona ao grupo VIP.',
    steps: [
      { text: 'Liberar acesso ao sistema Fyness (webhook)', done: false },
      { text: 'Enviar e-mail de boas-vindas com credenciais', done: false },
      { text: 'Enviar WhatsApp de boas-vindas + link de suporte', done: false },
      { text: 'Adicionar ao grupo VIP de clientes', done: false },
      { text: 'Enviar tutorial de primeiros passos', done: false },
    ],
    inputs: 'Pagamento confirmado via webhook',
    outputs: 'Cliente com acesso ativo e orientado',
    toolsResources: 'Fyness, E-mail marketing, WhatsApp API, CRM',
    responsible: 'Automação / CS',
    acceptanceCriteria: 'Acesso liberado em < 5 min e boas-vindas enviadas',
  },
  {
    elementId: 'Task_Webhook_Falha',
    elementType: 'task',
    title: 'Webhook — Detecta Falha no Pagamento',
    objective: 'Detectar automaticamente falhas no cartão e disparar sequência de downsell.',
    description: 'Webhook do gateway detecta: limite insuficiente, segurança do banco, dados incorretos. Dispara sequência automática de recuperação.',
    steps: [
      { text: 'Monitorar webhook de falha de pagamento', done: false },
      { text: 'Classificar motivo da falha (limite, segurança, dados)', done: false },
      { text: 'Disparar sequência de downsell automático (5 min)', done: false },
      { text: 'Registrar falha no CRM', done: false },
    ],
    inputs: 'Webhook de cartão recusado',
    outputs: 'Falha classificada, downsell disparado',
    toolsResources: 'Gateway de pagamento, CRM, WhatsApp API',
    responsible: 'Automação',
    acceptanceCriteria: 'Downsell enviado em < 5 min após falha',
  },
  {
    elementId: 'Task_WhatsApp_5min',
    elementType: 'task',
    title: 'WhatsApp Automático — Link Semestral (5 min)',
    objective: 'Recuperar pagamento com downsell automático de Anual para Semestral.',
    description: 'Automação 5 min após falha: envia link do plano Semestral (R$ 997) que costuma passar no cartão por ser valor menor.',
    steps: [
      { text: 'Aguardar 5 min após falha do pagamento Anual', done: false },
      { text: 'Enviar WhatsApp com link Semestral + script de recuperação', done: false },
      { text: 'Monitorar se lead clicou no link', done: false },
      { text: 'Registrar tentativa de recuperação no CRM', done: false },
    ],
    inputs: 'Pagamento Anual falhou',
    outputs: 'Link Semestral enviado automaticamente',
    toolsResources: 'WhatsApp API (ManyChat/Evolution), CRM',
    responsible: 'Automação',
    acceptanceCriteria: 'WhatsApp enviado em < 5 min com link funcional',
  },
  {
    elementId: 'Task_Checkout_Semestral',
    elementType: 'task',
    title: 'Checkout — Plano Semestral (R$ 997)',
    objective: 'Downsell automático: ticket menor, mais fácil de passar no cartão.',
    description: 'Segundo degrau: R$ 997/semestre (R$ 166,17/mês). Não exposto no site. Usado apenas como downsell quando Anual falha.',
    steps: [
      { text: 'Lead recebe link do Semestral via WhatsApp automático', done: false },
      { text: 'Monitorar pagamento via webhook', done: false },
      { text: 'Se aprovado → onboarding. Se falhou → escalado para vendedor', done: false },
    ],
    inputs: 'Link Semestral enviado ao lead',
    outputs: 'Pagamento aprovado ou escalado para vendedor',
    toolsResources: 'Hotmart, Asaas, CRM',
    responsible: 'Automação',
    acceptanceCriteria: 'Pagamento processado ou vendedor acionado',
  },
  {
    elementId: 'Task_Vendedor_Trimestral',
    elementType: 'task',
    title: 'Vendedor — Oferta Trimestral (Carta na Manga)',
    objective: 'Vendedor faz contato humano D+2 com oferta Trimestral para salvar o deal.',
    description: 'Degrau 3: Vendedor liga/manda WhatsApp com argumento "namora por 3 meses". R$ 561/trimestre. Não exposto no site.',
    steps: [
      { text: 'Aguardar D+2 após falha do Semestral', done: false },
      { text: 'LIGAR para o lead com script de "namoro de 3 meses"', done: false },
      { text: 'Se não atender: WhatsApp com argumento de teste pago', done: false },
      { text: 'Enviar link privado do Trimestral se aceitou', done: false },
      { text: 'Registrar resultado no CRM', done: false },
    ],
    inputs: 'Pagamento Semestral também falhou',
    outputs: 'Oferta Trimestral apresentada, resultado registrado',
    toolsResources: 'Telefone, WhatsApp, CRM',
    responsible: 'Vendedor',
    acceptanceCriteria: 'Contato humano feito e resultado registrado',
  },
  {
    elementId: 'Task_Checkout_Trimestral',
    elementType: 'task',
    title: 'Checkout — Plano Trimestral (R$ 561)',
    objective: 'Último recurso: teste pago com menor compromisso.',
    description: 'Degrau 3: R$ 561/trimestre (R$ 187/mês). Até 3x no cartão. Link privado, não exposto no site. Uso exclusivo para recuperação.',
    steps: [
      { text: 'Vendedor envia link privado do Trimestral', done: false },
      { text: 'Monitorar pagamento via webhook', done: false },
      { text: 'Se aprovado → onboarding', done: false },
    ],
    inputs: 'Lead aceitou oferta Trimestral do vendedor',
    outputs: 'Pagamento aprovado ou lead perdido definitivamente',
    toolsResources: 'Hotmart, CRM',
    responsible: 'Automação',
    acceptanceCriteria: 'Pagamento processado ou marcado como perdido',
  },
];

// ==================== GERADOR DE ORDENS ====================

/**
 * Gera todas as Ordens de Processo do Template Comercial V9 para um projeto.
 * Usa Supabase diretamente com batch upsert (evita fallback offline do serviceFactory).
 * Seguro para chamar múltiplas vezes — usa ON CONFLICT para pular duplicatas.
 *
 * @param {string} projectId - ID do projeto BPMN
 * @returns {Promise<{ created: number, skipped: number, errors: number }>}
 */
export async function generateTemplateProcessOrders(projectId) {
  if (!projectId) {
    console.warn('[templateProcessOrders] projectId é obrigatório');
    return { created: 0, skipped: 0, errors: 0 };
  }

  const now = new Date().toISOString();

  // Montar rows com IDs baseados no elementId (estável mesmo se reordenar o array)
  const rows = TEMPLATE_PROCESS_ORDERS.map((def) => ({
    id: `po_tpl_${projectId.slice(-8)}_${def.elementId}`,
    project_id: projectId,
    element_id: def.elementId,
    element_type: def.elementType,
    title: def.title,
    description: def.description,
    objective: def.objective,
    steps: (def.steps || []).map((s, idx) => ({
      id: idx + 1,
      order: idx,
      text: s.text || '',
      details: '',
      required: true,
    })),
    inputs: def.inputs,
    outputs: def.outputs,
    tools_resources: def.toolsResources,
    responsible: def.responsible,
    participants: '',
    acceptance_criteria: def.acceptanceCriteria,
    risks: [],
    improvements: [],
    lessons_learned: '',
    status: 'draft',
    version: 1,
    notes: '',
    created_at: now,
    updated_at: now,
  }));

  // Inserir em batches de 20 (evita payload gigante)
  const BATCH_SIZE = 20;
  let created = 0;
  let skipped = 0;
  let errors = 0;

  for (let i = 0; i < rows.length; i += BATCH_SIZE) {
    const batch = rows.slice(i, i + BATCH_SIZE);

    // Remove created_at pra não sobrescrever data original em updates
    const batchForUpsert = batch.map(({ created_at, ...rest }) => rest);

    const { data, error } = await supabase
      .from('process_orders')
      .upsert(batchForUpsert, {
        onConflict: 'project_id,element_id',
      })
      .select('id');

    if (error) {
      console.error('[templateProcessOrders] Batch erro:', error.message);
      errors += batch.length;
    } else {
      created += (data || []).length;
      skipped += batch.length - (data || []).length;
    }
  }

  console.log(
    `[templateProcessOrders] Resultado: ${created} criadas, ${skipped} já existiam, ${errors} erros`
  );

  return { created, skipped, errors };
}

/** Retorna a quantidade total de ordens definidas no template */
export function getTemplateProcessOrderCount() {
  return TEMPLATE_PROCESS_ORDERS.length;
}
